### ISSUE TITLE
SSL 

### ISSUE THREAD

**Issue by cjshort** [amro/gibbon#106]
Controller:
  def subscribe
  @list_id = "01d4743206"
  @gb = Gibbon::API.new
  @gb.lists.subscribe({:id => @list_id, :email => {:email => 'callumshorty@hotmail.com'}, :merge_vars => {:FNAME => 'First Name', :LNAME => 'Last Name'}, :double_optin => false})
  end

Gibbon.rb initializer:
 Gibbon::API.api_key = "5dbfa9b02dd8a28aa43937d19855da6e-us9"
  Gibbon::API.timeout = 15
  Gibbon::API.throws_exceptions = false

View:
        <%= form_tag('/posts/subscribe', method: "post", id: "subscribe", remote: "true") do %>
            <div class="large-18 columns text-right mailer">
            <%= email_field(:email, :address, {id: "mailersub", placeholder: "Enter your email"}) %>
            </div>
            <div class="large-6 columns text-right mailer">
                <%= submit_tag("Submit", id: "mailersubmit") %>
            </div>
        <% end %>

Routes:
  post 'posts/subscribe' => 'posts#subscribe'

Error:
Started POST "/posts/subscribe" for 127.0.0.1 at 2014-11-25 10:26:23 +0000
Processing by PostsController#subscribe as JS
  Parameters: {"utf8"=>"✓", "email"=>{"address"=>"callumshorty@hotmail.com"}, "commit"=>"Submit"}
Completed 500 Internal Server Error in 92ms

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
  app/controllers/posts_controller.rb:11:in `subscribe'

**Comment by rvgarimrj** [comment]
Can anyone help please ?
I'm getting the following message:

Gibbon::MailChimpError - Signup disabled
/Users/gabrielmadeira/.rvm/gems/ruby-2.1.1/bundler/gems/gibbon-1d8ee00f576d/lib/gibbon/api_category.rb:47:in `call'
/Users/gabrielmadeira/.rvm/gems/ruby-2.1.1/bundler/gems/gibbon-1d8ee00f576d/lib/gibbon/api_category.rb:57:in `method_missing'
app/models/user.rb:66:in `add_user_to_mailchimp'

User Model:
class User < ActiveRecord::Base
rolify
# Include default devise modules. Others available are:
# :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable, :confirmable,
:recoverable, :rememberable, :trackable, :validatable
# Setup accessible (or protected) attributes for your model
attr_accessible :name, :email, :password, :password_confirmation, :remember_me
after_create :add_user_to_mailchimp
before_destroy :remove_user_from_mailchimp
# override Devise method
# no password is required when the account is created; validate password when the user sets one
validates_confirmation_of :password
def password_required?
if !persisted?
!(password != "")
else
!password.nil? || !password_confirmation.nil?
end
end
# override Devise method
def confirmation_required?
false
end
# override Devise method
def active_for_authentication?
confirmed? || confirmation_period_valid?
end
def send_reset_password_instructions
if self.confirmed?
super
else
errors.add :base, "You must receive an invitation before you set your password."
end
end
# new function to set the password
def attempt_set_password(params)
p = {}
p[:password] = params[:password]
p[:password_confirmation] = params[:password_confirmation]
update_attributes(p)
end
# new function to determine whether a password has been set
def has_no_password?
self.encrypted_password.blank?
end
# new function to provide access to protected method pending_any_confirmation
def only_if_unconfirmed
pending_any_confirmation {yield}
end
private
def add_user_to_mailchimp
return if email.include?(ENV['ADMIN_EMAIL'])
mailchimp = Gibbon::API.new(ENV['MAILCHIMP_API_KEY'])
result = mailchimp.lists.subscribe({
:id => ENV['MAILCHIMP_LIST_ID'],
:email => {:email => self.email},
:double_optin => false,
:update_existing => true,
:send_welcome => true
})
Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
end
def remove_user_from_mailchimp
mailchimp = Gibbon::API.new(ENV['MAILCHIMP_API_KEY'])
result = mailchimp.lists.unsubscribe({
:id => ENV['MAILCHIMP_LIST_ID'],
:email => {:email => self.email},
:delete_member => true,
:send_goodbye => false,
:send_notify => true
})
Rails.logger.info("Unsubscribed #{self.email} from MailChimp") if result
end
end

initializer/mailchimp.rb:

if Rails.env.test?
Gibbon::Export.api_key = "fake"
Gibbon::Export.throws_exceptions = false
end
Rails.configuration.mailchimp = Gibbon::API.new(ENV['MAILCHIMP_API_KEY'])

**Comment by amro** [comment]
You really should contact MailChimp API support about "Signup disabled." Your account might be locked or something along those lines. I really don't know as I've never seen that error..

**Comment by amro** [comment]
To be clear, Gibbon is a 3rd party wrapper for MailChimp's API. I don't work for MailChimp or provide support for their API.
