### ISSUE TITLE
Mailchimp subscribtion // No error, no new record updates

### ISSUE THREAD

**Issue by bbnnt** [amro/gibbon#108]
Everything works very smoothly using Gibbon (thanks for making this very easy to use!)

Playing around the gem in the console, no errors.

But I have a problem : nothing shows up in the subscribers list, in the mailchimp admin
So I'm asking what is it that go wrong right here ? is there a special parameter to add (I'm doing plain list/email via a simple gb.lists.subscribe({:id => MAILCHIMP_LIST, :email => {:email => self.email}}) )

Key is ok, list is ok, plugin is perfect… BUT !
Thanks if any feedback/help

**Comment by amro** [comment]
My best guess is you need to confirm the email address you're attempting to subscribe. By default, MailChimp enables double opt-in. If you don't confirm the email, it will not appear in your list. Check their API doc for the name of the param you should pass to disable this but I recommend leaving it enabled. Your list will be of a much higher quality if you do. Let me know whether this helps.

**Comment by bbnnt** [comment]
OOOOkkkkkay ! Sorry for this post. I can see when ruby code/gem work, but i'm a total newbie on mailchimp
That will obviously be the reason; thanks for pointing this out

**Comment by amro** [comment]
No problem at all, have a good one!
