### ISSUE TITLE
Mail Validation error

### ISSUE THREAD

**Issue by hansfindel** [amro/gibbon#111]
Hello, 

Trying to add users in a batch. 

It throws this error foreach user:

    {"code"=>-99, "error"=>"An email address must contain a single @", "email"=>"xxxxx@gmail.com"}

The email has only one "@".

Thanks

**Comment by amro** [comment]
Are you URL encoding your request body?

Thanks,
Amro

**Comment by hansfindel** [comment]
I am using the gem to do all the work, following the Readme. 

    chimp = Gibbon::API.new xxxxxxxxx
    #... get the list_id  
    chimp.lists.batch_subscribe({ id: @list_id, batch: batch_data })

Where batch_data has the users in the json-structure for the gem
(like this one  {email: {email: user.email},  merge_vars: [{"key1": "value1"}]}  )

**Comment by amro** [comment]
That should be correct. I'm away from my machine until Saturday. Will look at this then. Sorry for the trouble.

Thanks,
Amro

**Comment by hansfindel** [comment]
Solved

The problem had something to do with the batch_data. I created it a little sooner and now it works. 

Thanks anyways.
