### ISSUE TITLE
Email already subscribed issue.

### ISSUE THREAD

**Issue by Sohair63** [amro/gibbon#115]
Usecase: A user subscribed through my program and receives an email from mailchimp subscription, but didn't click on subscribed button, so user is not get into the list of mailchimp.

Next time, user again subscribed so he should again receive an email, that is correct. It goes good. 
Now if I check that,
    gb = Gibbon::API.new(APP_CONFIG[:mailchimp][:api_key])
     info = gb.lists.member_info({id: APP_CONFIG[:mailchimp][:list_id], emails [{email: params[:subscribe_email]}]})
     result = info['data'].find { |h|  h['email'] }
     if result && result['email'] == params[:subscribe_email]
        @error = "Email is already subscribed to the list."

**result['email']** returns the email that i have not subscribed yet but received an email. and this email also does not exist in mailchimp list.

**Comment by amro** [comment]
Gibbon wraps the MailChimp API and this is how the API works. You should contact MailChimp support if you're confused by that behavior but first I recommend checking whether the `update_existing` parameter might be useful to you. You've described what's happening but not really what you're trying to achieve so I'm afraid I can't help much.

More info in the [lists/subscribe docs](https://apidocs.mailchimp.com/api/2.0/lists/subscribe.php).

**Comment by Sohair63** [comment]
Thanks for your help. I get member info with the parameter status:
"subscribed" that resolved my issue.

On Thursday, 26 February 2015, Amro Mousa <notifications@github.com> wrote:

> Gibbon wraps the MailChimp API and this is how the API works. You should
> contact MailChimp support if you're confused by that behavior but first I
> recommend checking whether the update_existing parameter might be useful
> to you. You've described what's happening but not really what you're trying
> to achieve so I'm afraid I can't help much.
>
> More info in the lists/subscribe docs
> <https://apidocs.mailchimp.com/api/2.0/lists/subscribe.php>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amro/gibbon/issues/115#issuecomment-76208572>.
>


-- 


Regards,

Sohair S. Ahmad.

**Comment by amro** [comment]
Glad you figured it out, @Sohair63!
