### ISSUE TITLE
Error with test env and factorygirl - must set api key prior to making call

### ISSUE THREAD

**Issue by jakeatwork** [amro/gibbon#116]
Error message:
Failure/Error: user = FactoryGirl.create(:user)
     Gibbon::GibbonError:
       You must set an api_key prior to making a call

I've tried to set the test env api key in any number of ways, but either i'm butchering the syntax/location for that definition or something else is not working. 

I searched high and low for resolution to this, but couldn't discover anything. Probably something obvious...any guidance appreciated.

Everything works fine in dev/prod env, I just can't get my tests working. Thanks.

**Comment by amro** [comment]
Have you tried setting Gibbon::API.api_key = "yourtest-key" during setup for your tests?

Otherwise, is there any chance you could send me a simple sample project (obviously not your real code) that I could tinker with to try to help find a solution?

**Comment by jakeatwork** [comment]
DOH. figured it out right after i posted. i was trying to access the rails secrets.yml version of the env variable in spec helper, but just needed to access the ENV variable directly because spec helper is reading from my .env file. all tests green. thanks!
