### ISSUE TITLE
Get a template

### ISSUE THREAD

**Issue by loureirorg** [amro/gibbon#117]
Is there any way to get a template from a MailChimp account? The MailChimp API 2.0 has many template methods (https://apidocs.mailchimp.com/api/2.0/#templates-methods), but Gibbon support it?

**Comment by amro** [comment]
Any API 2.0 methods should work fine with Gibbon.

**Comment by loureirorg** [comment]
but how? I had tried this:

```ruby
gb = Gibbon::API.new
gb.templates.list
```
And the return was:
```ruby
=> {"user"=>[], "gallery"=>[], "base"=>[]}
```
But there are templates in MailChimp, so why this is empty?

PS: I set the `api_key` on config/initializers/gibbon.rb. `gb = Gibbon::API.new` it's working, I had tested with `gb.lists.list` and returned me correct data.

**Comment by amro** [comment]
Sorry that I didn't get back to you on this. I was traveling for literally half of April and it fell through the cracks. That response is from the server so the issue would have been on MC's end.

**Comment by martinverdejo** [comment]
I did the following, and it worked.

```
gb = Gibbon::Request.new(api_key: API_KEY)
gb.templates.retrieve
```
