### ISSUE TITLE
Update to Mailchimp API v3.0?

### ISSUE THREAD

**Issue by nellshamrell** [amro/gibbon#118]
I noticed that Mailchimp has release version 3.0 of their API [here](http://blog.mailchimp.com/announcing-mailchimp-api-v3-0/).

Are you interested in updating Gibbon to for Mailchimp API v3.0?  I'd be happy to help if I can!  But first I wanted to make sure this was something you would be interested in.

Thanks!

**Comment by amro** [comment]
Hi Nell. Yes, I am. I'm in the process of rethinking how Gibbon might work to support the new API right now. I'm not happy with how Gibbon is built at the moment.

**Comment by amro** [comment]
For example, API 3 supports multiple HTTP verbs per endpoint. Thinking out loud, the syntax might look like:

    gibbon.get.lists(list_id).interest_categories(category_id).interests(id)

Creating a new object might look like:

    gibbon.post.campaigns(campaign)

It's weird to leak the http verb into the syntax. I'm not a fan of that and open to ideas to fix it. Still thinking on this.

Feedback or suggestions welcome.

**Comment by daveespo** [comment]
I don't see much way around it and there are other libraries that have done the same. However, the verb tends to be at the end of the resource string, not the beginning. And, taking the Stripe Ruby library as an example, it uses the CRUD verbs rather than raw HTTP verbs

https://stripe.com/docs/api/ruby#create_card

So, your above example would be more like

````
gibbon.lists(list_id).interest_categories(category_id).interests(id).retrieve

gibbon.lists(list_id).interest_categories(category_id).interests(id).update(payload)
````

**Comment by amro** [comment]
Cool. Thanks for sharing. That's very helpful. I'll make time to start working on this. Help testing would be especially appreciated, once I have something to share.

**Comment by nellshamrell** [comment]
Absolutely!  Please send me a ping when you're ready for some testing :)

**Comment by amro** [comment]
Just a heads up that I have started on this.

**Comment by nellshamrell** [comment]
Huzzah!! :smile_cat:

**Comment by amro** [comment]
Fetching lists works now. I need to test other resources and add actual tests, plus do a little more work to make sure errors from the http lib (switched rest-client but not sure it's best yet) are handled properly.

**Comment by amro** [comment]
Usage looks a like this (currently):

    g = Gibbon::Request.new(api_key: "mykey-us1")
    g.lists.retrieve(params: {foo: "bar"}, headers: {headername: "value"})

Supports params, headers, and body depending on the HTTP verb so that'll cover things like filters, etc. Values that go in the url, like IDs, work as we discussed above.

**Comment by nellshamrell** [comment]
Looking good!

When this is ready for testing, I'd be happy to both test and update the command examples in the README.

**Comment by amro** [comment]
Take a look at https://github.com/amro/gibbon/tree/api_v3 when you have time. The tests are completely out of date/broken. Part of the readme has been updated. From "Fetching Campaigns" to  "Error Handling" needs to be updated. To be clear, the "Error Handling" section has been updated.

To be honest, I don't know what params are available on some of these calls to do things like filter, paginate, etc. I made my best effort to support headers, query params, and post body to cover that sort of thing. I think the API docs are not quite complete yet.

Please send any pull requests against the api_v3 branch. I do prefer a single squashed commit, if possible.

**Comment by amro** [comment]
Ah, FYI, there's one issue I've not figured out yet. There are some internal methods in ::APIRequest. I still need to mark them private but I was having issues calling them from a public method on that class. I moved on in the interest of time but I will revisit it. Maybe later tonight.

**Comment by amro** [comment]
Another update: I fixed some of the tests, commented the rest out for now. Examples in README (as mentioned above) still need to be updated and more tests need to be updated or replaced. Still working from the api_v3 branch.

**Comment by nellshamrell** [comment]
Will take a look tonight!

**Comment by nellshamrell** [comment]
Partly through the README, updating as I go along.  Will continue tomorrow morning.

**Comment by amro** [comment]
Awesome, thanks!

**Comment by amro** [comment]
Here's an example of subscribing a user, if you've not already figured it out:
    g.lists(list_id).members.create(body: {email_address: email_address, status: "subscribed"})

**Comment by nellshamrell** [comment]
Thanks!  That's a big help, I was missing the "body" part :)

**Comment by nellshamrell** [comment]
Hmm...that's giving me an error:

2.1.2 :018 > gb.lists(list_id).members.create({body: {email_address: "nshamr@uw.edu", status: "subscribed"}})
Gibbon::MailChimpError: undefined method `bytesize' for {:email_address=>"nshamr@uw.edu", :status=>"subscribed"}:Hash

**Comment by nellshamrell** [comment]
Troubleshooting

**Comment by nellshamrell** [comment]
I'm kind of stumped on this one.

**Comment by amro** [comment]
Pull latest from the branch to fix that. I wasn't json encoding the body bc I thought Faraday would do that given the wording in its readme. Apologies!

Thanks,
Amro

**Comment by nellshamrell** [comment]
Will do!

**Comment by nellshamrell** [comment]
Works like a charm now :)

**Comment by nellshamrell** [comment]
Sent an email to Mailchimp asking for some examples of creating a campaign and paginating responses to queries (even when using offset and count as detailed in this article http://kb.mailchimp.com/api/article/api-3-overview)

Will add those once I have working examples based on Mailchimp's examples :)

**Comment by amro** [comment]
Thanks very much

**Comment by nellshamrell** [comment]
Just heard back from MailChimp:

Thanks for reaching out. At this time, campaign creation methods aren't available in v3.0 of the API. You'll need to continue using the v2.0 endpoints for now to create campaigns, but it's on the roadmap for 3.0: https://apidocs.mailchimp.com/api/2.0/campaigns/create.php

To paginate using v3.0 of the API, you'll want to add the "count" and "offset" parameters as query strings to the endpoint URL. For example, if I wanted to grab campaigns 301-400, I'd make a GET request to the following endpoint:

https://usX.api.mailchimp.com/3.0/campaigns?count=100&offset=300

Will add some count and offset parameter examples as I have time.

**Comment by amro** [comment]
Thanks Nell. Sounds good. I’ll keep testing and try to write a few more unit tests I get time as well.

**Comment by duboff** [comment]
Hi, I was wondering where the update is these days. Is the v3.0 branch ready to try out?

**Comment by amro** [comment]
You can try out the api_v3 branch, yes. There are no known bugs but I'm waiting on some tests someone has graciously offered to contribute.

I intend to push one more release of Gibbon 1.x that will adds support. This was contributed recently by @fsluis.

**Comment by duboff** [comment]
Cool, I'll keep you guys posted.

**Comment by amro** [comment]
I pushed a prerelease version of v2: just `gem install gibbon --pre` to get it

https://rubygems.org/gems/gibbon/versions/2.0.0.pre

I'll promote to prod once it's been out there for a little while.

**Comment by amro** [comment]
Has anyone on this thread run into issues?

**Comment by lachlanhardy** [comment]
I've been using it for a simple list subscriptions and it's all good. Thanks for working on this!

**Comment by amro** [comment]
@lachlanhardy Thanks for the feedback. It's super helpful. I'll release really soon.

**Comment by amro** [comment]
I released v2

**Comment by lachlanhardy** [comment]
Yay, thanks! Now using it in production :)
