### ISSUE TITLE
Installation - Step 4 - Duplicate column name 

### ISSUE THREAD

**Issue by nobicycle** [amro/gibbon#122]
Fresh install from Github:
I selected install demo data

ENV
====
php -v
PHP 5.6.10 (cli) (built: Jun 11 2015 19:50:24) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
[user@tower Education]$ mysql -V
mysql  Ver 15.1 Distrib 10.0.19-MariaDB, for Linux (x86_64) using readline 5.1
[user@tower Education]$ uname -a
Linux tower 4.0.5-1-MANJARO #1 SMP PREEMPT Sat Jun 6 19:29:16 UTC 2015 x86_64 GNU/Linux

ERROR
======

Installation - Step 4
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'replacementCost'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Messenger-Message Bubble Width Type' for key 'scope'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Messenger-Message Bubble Background Color' for key 'scope'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Messenger-Message Bubble Auto Hide' for key 'scope'SQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 rowSQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 rowSQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 rowSQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 rowSQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 rowSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'gibbonUnitBlockStar' already existsSQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'languageHome'
Congratulations, your installation is complete. Feel free to go to your Gibbon homepage and login with the username and password you created.

It is also advisable to follow the Post-Install and Server Config instructions.

**Comment by amro** [comment]
You've posted this issue to the wrong project. This project is a Ruby gem that lets one interact with the MailChimp API.
