### ISSUE TITLE
Breaking change in export.rb

### ISSUE THREAD

**Issue by nickmalcolm** [amro/gibbon#125]
In https://github.com/amro/gibbon/commit/0fcffa45b371c7bf40b6d23fc5d3149ad0ac1202#diff-20502efd9163d9cdc91dd052e2faa268L24 and https://github.com/amro/gibbon/commit/589c81f453bbe9a08d975bbf3c9aa0ea2423f296#diff-20502efd9163d9cdc91dd052e2faa268R42 you changed the return type of `export.list`.
It was an Array of strings (body.lines), now it's an array of array of string (via `split_json`). This was a breaking change for us and the versioning didn't indicate that (`1.1.5` -> `1.1.6`). :/

Also your `split_json` method seems error prone - I haven't had time to test it but I'm pretty sure someone with a name like `"My Name {} lololol [][]"` will cause problems?

Anyhoo, we've worked around it for now, but I figured I'd flag this. It might be worth using something like `Yajl` to parse the response's lines, instead of doing a funky `split`.

I'll try add more to this issue when I have time. :)

**Comment by amro** [comment]
@nickmalcolm The versioning is definitely an oversight on my part. I will yank 1.1.6 and re-release it as 1.2.0. I know the damage is already done there - please accept my apologies.

I see your point about split_json(). I'm not sure what to do there other than not handle that error case (or revert streaming support entirely).

**Comment by nickmalcolm** [comment]
All good! I appreciate your hard work :)

**Comment by amro** [comment]
This should be good to go. I removed the hack in split_lines(). I couldn't reproduce the lack of a newline. I did keep the type the same, as I mentioned above, because I think having it pre-parsed makes sense.
