### ISSUE TITLE
Member deletion raises error on success

### ISSUE THREAD

**Issue by romikoops** [amro/gibbon#126]
When member was deleted successfully api v3 returns 204 status and empty body. But in code we are trying to parse json from body. As result - parsing error

**Comment by amro** [comment]
Thanks for the heads up! I'll look into this (hopefully later tonight) unless you're interested in sending a pull request.

**Comment by amro** [comment]
Fix was trivial so I went ahead and released 2.0.0.1.pre. Please give it a go. Thanks again for the bug report!

**Comment by romikoops** [comment]
thanks a lot, it works now!

**Comment by amro** [comment]
No problem at all. How long have you used 2.0.0? Any feedback? I'd like to release it as a production build soon.

**Comment by romikoops** [comment]
Our company talendo.ch is doing close integration with MailChimp now. I did 50% of all tasks. I am going to finish everything tomorrow, after that I will have ability to provide feedback
