### ISSUE TITLE
Subscription error

### ISSUE THREAD

**Issue by mrtorks** [amro/gibbon#128]
I tried using your gem to subscribe to my mail chimp list but there is one problem it passes without errors but i don't see the email in my list. I have gone through all the docs but I seem not to get a hand on the bug that causes this

**Comment by amro** [comment]
Subscriptions with gibbon work fine. My guess is the email needs to opt in (double opt-in is enabled by default on MC lists) by clicking the link in the email MailChimp sends them.

On Aug 8, 2015, at 10:52 PM, mrtorks <notifications@github.com> wrote:

I tried using your gem to subscribe to my mail chimp list but there is one problem it passes without errors but i don't see the email in my list. I have gone through all the docs but I seem not to get a hand on the bug that causes this

**Comment by mrtorks** [comment]
i passed this parameter :double_optin => false, hence they actually don't have to opt in, I want to know whether it's something related to mailchimps's API 3.0. Every test i ran on my production server passes but i check the subscription list I created on mail chimp and the email is not there at all. It says 0 subscribers

**Comment by amro** [comment]
When you say tests on your production servers pass, do you mean you do not receive an error from the MC API? e.g. Does it return a 4xx error or something along those lines?

I’m sorry but I don’t have enough information to figure out what’s happening yet.

On Aug 8, 2015, at 11:01 PM, mrtorks <notifications@github.com> wrote:

i passed this parameter :double_optin => false, hence they actually don't have to opt in, I want to know whether it's something related to mailchimps's API 3.0. Every test i ran on my production server passes but i check the subscription list I created on mail chimp and the email is not there at all. It says 0 subscribers

**Comment by mrtorks** [comment]
app/controllers/openhwy_controller.rb:15:in `subscribe' 
Aug 08 19:44:26 serieux-chaise-7140 heroku/router:  at=info method=POST path="/subscribe" host=www.openhwy.com request_id=565c7ab0-ccad-4281-88b8-edf4cc74ad50 fwd="70.65.88.9" dyno=web.1 connect=1ms service=21ms status=302 bytes=981 
Aug 08 19:44:26 serieux-chaise-7140 app/web.1:  Started POST "/subscribe" for 70.65.88.9 at 2015-08-09 02:44:26 +0000 
Aug 08 19:44:26 serieux-chaise-7140 app/web.1:  Processing by OpenhwyController#subscribe as HTML 

The above indicated that the email was subscribed to the list successfully. It did return errors at first and I was informed about the error you pointed out previously about the opt in default setting. I fixed that by passing the parameter to override that feature however, heroku returns a status 300 but my list on Mailchimp is empty indicating that the subscription process failed silently. Where that happened, I have no idea of it. I also readied my mail chimp vars.

**Comment by amro** [comment]
Those log statements seem to be for your server, not MailChimp API. Try loading up irb (or the Rails console, whichever) and trying the snippet of code you're using to hit MC's API directly and nothing else. This way you're isolating it from the rest of your code.

**Comment by mrtorks** [comment]
irb(main):013:0> gibbon.lists.members.create(body: {email_address: "email_address", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})
Gibbon::MailChimpError: the server responded with status 404
	from /app/vendor/bundle/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:100:in `handle_error'
	from /app/vendor/bundle/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:16:in `rescue in post'
	from /app/vendor/bundle/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:10:in `post'
	from /app/vendor/bundle/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/request.rb:28:in `create'
	from (irb):13
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'

now I have no clue. I guess this is where the true error is. I guess ou could help then

**Comment by amro** [comment]
Okay - so you're getting a 404. It usually responds with that if the member is already subscribed. You can verify that by rescuing the error and checking the [populated fields](https://github.com/amro/gibbon/blob/master/lib/gibbon/mailchimp_error.rb).

**Comment by mrtorks** [comment]
I figured out why it was not working. Thanks for the help @amro

**Comment by mrtorks** [comment]
i guess i was not using the syntax in your README.md but rather using the syntax for api 2.0

**Comment by tubbo** [comment]
Hi, I'm using the new 2.0 syntax and still get this error:

```ruby
mailchimp = Gibbon::Request.new 
mailchimp.lists(LIST_ID).members.create(body: {email_address: "foo@bar.com", status: "subscribed", merge_fields: {FNAME: "Bob", LNAME: "Smith"}})
```

I get the following error when I run this:

```
Gibbon::MailChimpError: the server responded with status 404
from /.../vendor/bundle/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:100:in `handle_error'
```

**Comment by amro** [comment]
Try printing error.raw_body to see the specific error the MailChimp API is returning

Thanks,
Amro

**Comment by tubbo** [comment]
Here's what I got:

```
{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Resource Not Found","status":404,"detail":"The requested resource could not be found.","instance":""}
```

**Comment by amro** [comment]
@tubbo Are you setting an API key elsewhere? Can you try printing `mailchimp.api_key`?

**Comment by novarac23** [comment]
Currently experiencing the same problem as @tubbo did. What's weird about it is it worked yesterday in production and it worked on our staging instance. Anything weird happening with mailchimp that I am not aware of or ?

**Comment by amro** [comment]
This is a general error. Have you printed the exception to see what happened in your specific case?

**Comment by novarac23** [comment]
@amro We solved the issue, and it was not in Gibbon. It was that we used `heroku fork` and that copied `api_key`s as well, which caused the issue. Sorry about this!

**Comment by amro** [comment]
No problem. It could just as easily have been my mistake.

**Comment by novarac23** [comment]
Actually at one point it became really fun because I started looking in the source code of the gem and trying to figure out whats causing the issue. Open source geek was happy :)

**Comment by amro** [comment]
I hope you found the source easy to follow. I tried to keep v2 really simple. :)

**Comment by novarac23** [comment]
Yeah it was actually pretty straight forward. Good job :+1:

**Comment by zephiro** [comment]
How to subcriber member with doubleopt false?

`mailchimp.lists(LIST_ID).members.create(body: {email_address: "foo@bar.com", status: "subscribed", merge_fields: {FNAME: "Bob", LNAME: "Smith"}})`

**Comment by amro** [comment]
Using 'subscribed' status disables double opt-in. Please look at MailChimp's documentation for API issues as it's the source of truth. Here's their knowledge base article about this: http://kb.mailchimp.com/api/article/how-to-manage-subscribers

**Comment by Jirka1111** [comment]
I have still the same error.
gibbon.api_key gives me the right api key. But error 404 (same as tubbo) is still there.

gibbon.lists("my_list_key").members.create(body: {email_address: "foo@bar.com", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})

Even this test request gives me 404. I am not setting api key elsewhere.

**Comment by amro** [comment]
This member might already be part of your list. Try a different email or try an upsert instead.

Thanks,
Amro

**Comment by Jirka1111** [comment]
@amro It is not. My subscribers list is empty.

Thank you.

**Comment by amro** [comment]
Let's stick to one issue, please. It'll be hard to keep track of a conversation in two places.

**Comment by Jirka1111** [comment]
Yes, please. I will end discussion here.

**Comment by justinedps26** [comment]
HI, i also have this issue. It was working fine before. Here is my code:

`# gibbon.rb

Gibbon::Request.api_key = "<%= ENV[MAILCHIMP_API_KEY] %>"
Gibbon::Request.timeout = 15
Gibbon::Request.throws_exceptions = false
`

` # user.rb

def add_to_list
    list_id = ENV['MAILCHIMP_LIST_ID']
    @gb = Gibbon::Request.new(api_key: ENV['MAILCHIMP_API_KEY'])
    subscribe = @gb.lists(list_id).members.create(
      body: {email_address: self.email, status: "subscribed", double_optin: false}
    )
  end
` 

Where do you think the error could come from?

Thanks :)

**Comment by amro** [comment]
@justineedps26, could you please share the error returned by the API?

One thing to look at is using “upsert” instead of “create.” See the readme for deals on how. The MC’s API will return an error upon creation if a member has previously been added to a list and unsubscribed.


P.s. In the future could you please open a new ticket? I’m happy to try to help but reusing issues introduces confusion (for me at least!). Thank you.

**Comment by justinedps26** [comment]
Hi @amro, sorry i thought the issue was still open.

Here is the error i got:

`Gibbon::MailChimpError: the server responded with status 404 @title="Resource Not Found", @detail="The requested resource could not be found.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Resource Not Found", "status"=>404, "detail"=>"The requested resource could not be found.", "instance"=>"4ba9dda5-8907-43d9-b8d3-b455ac472dea"}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Resource Not Found\",\"status\":404,\"detail\":\"The requested resource could not be found.\",\"instance\":\"4ba9dda5-8907-43d9-b8d3-b455ac472dea\"}", @status_code=404`

**Comment by amro** [comment]
I don’t have enough info to know exactly what’s happening. The first thing I would check is whether your list_id is valid. Try hard coding it instead of fetching it from environment variables. If that works then you know it’s not being set properly as an environment variable.

**Comment by justinedps26** [comment]
Hard coding the list_id made it work!
