### ISSUE TITLE
Heroku Setting for gibbon

### ISSUE THREAD

**Issue by mrtorks** [amro/gibbon#129]
Sorry amro,

It was quite hard to resist but I have a problem. For some reason as you suggested I used the console to figure out the right syntax to use but however, it seems my controller cannot access the ENV[MAILCHIMP_LIST_ID] I set on heroku. It keeps giving me a 404. Is there a way to set these values which so they can be accessible in a controller. since its not clear in the docs

This is my code

def subscribe

		gb = Gibbon::Request.new
	    list_id = ENV["MAILCHIMP_LIST_ID"]
	    email = params[:email]
		subscribe = gb.lists(list_id).members.create(body: {email_address: email, status:    "subscribed", merge_fields: {FNAME: "NotifyMeSubscriber", LNAME: "NotifyMeSubscribe"}})
			if subscribe
			    redirect_to :back, notice: " Congrats You're in the mailing list"
			end	

    end

**Comment by amro** [comment]
To set an environment variable while using the console, you can do something like:

    MAILCHIMP_LIST_ID=value rails c

When you start the console. This is not specific to Gibbon.

**Comment by mrtorks** [comment]
Everything works in the console and I believe your code would work. However how to set it permanently in the app so the controller can access the list_id in the production environment. My problem is that this line:

    subscribe = gb.lists(list_id).members.create(body: {email_address: email, status:    "subscribed", merge_fields: {FNAME: "NotifyMeSubscriber", LNAME: "NotifyMeSubscribe"}})


does not work in the production environ meant and this is the error I get:

Gibbon::MailChimpError (the server responded with status 404): 
Aug 09 02:54:26 serieux-chaise-7140 app/web.1:    app/controllers/openhwy_controller.rb:15:in `subscribe'

**Comment by amro** [comment]
Right! So log the error so you can see what's wrong. Log the values for list_id and email as well. At this point you just need to debug your code. You're on the right track! :)

**Comment by mrtorks** [comment]
I am new to using this gem, so I would politely ask how to log the error

**Comment by amro** [comment]
That is specific to your application, not to this gem. In a Rails app, you might do something like:

    Rails.logger.info("error: #{e}")

In the rescue block. If you're using some other framework or doing something custom then I don't know - you'll want to look it up for that framework or see how you've logged other values in your app.

**Comment by CanvasCut** [comment]
You could just use "puts" as well.  It will still show up in the Heroku logs.

mrtorks, did you confirm that ENV["... mailchimp list id"] is actually set?  Also, may I ask why you're even making that an environment variable?

**Comment by amro** [comment]
@mrtorks Did you figure out what's wrong w/ your controller code? Are you specifying the values as environment variables?

**Comment by mrtorks** [comment]
Yes I did amro and you should know this the controller could not find the end
variable I set for list_id. You should work on that or find a workaround it

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.4.21&pv=8.3]
On Kwe, D-Ɔ 9, 2015 at 1:21 EW, amro/gibbon
<reply@reply.github.com>
wrote:
@mrtorks [https://github.com/mrtorks] Did you figure out what's wrong w/ your controller code? Are you specifying the
values as environment variables?

—
Reply to this email directly or view it on GitHub
[https://github.com/amro/gibbon/issues/129#issuecomment-129227316] .[https://github.com/notifications/beacon/AMq2r7_nJODhF7nW727tkQObqSlnPM3Zks5ol5-5gaJpZM4FoLZJ.gif]

**Comment by mrtorks** [comment]
Okay guys,
This gem works good but o
has one problem.

For some weird reason it cannot find the list_id set in the env config vars list especially on heroku there fore:

list_id = ENV['MAILCHIMP_LIST_ID']

does not work at all.

My work around was to include the raw list_id value. before it worked.

**Comment by mrtorks** [comment]
and @CanvasCut i confirmed it and everything was fine

**Comment by amro** [comment]
The controller not finding the list_id variable has literally nothing to do with this gem and everything to with the code you've written and your environment. I think your environment variable is not configured correctly, but it's really difficult for me to debug that on my end. I did find this [blog post](http://tammersaleh.com/posts/managing-heroku-environment-variables-for-local-development/) that explains how one might go about setting environment variables but I don't use Heroku so I can't verify whether it's up to date, etc. but I hope it's helpful in the future.

Anywho, I'm glad you have a workaround. Best of luck getting env variables working on Heroku.

**Comment by mrtorks** [comment]
Thank you very much @amro
