### ISSUE TITLE
Advice? Handling exceptions in ActiveJob

### ISSUE THREAD

**Issue by DanielKehoe** [amro/gibbon#132]
This is a request for advice, rather than reporting an issue, and if you want to close it and tell me go to Reddit, I won't feel bad.

I'm using Gibbon inside of an ActiveJob ```perform``` method. My application is broken because I'm using the Gibbon 2.0 gem with Gibbon 1.0 code and getting the error ```NameError: uninitialized constant Gibbon::API```. I know how to fix that. But I realize that I should be handling the exception. To the user, the application appears to work because the failure occurs in ActiveJob after the user already sees a response. I only know there is a failure because no result appears in my Mailchimp account and I see an error when I analyze my log files.

How do you handle a Gibbon exception inside of ActiveJob? I suppose I could email an administrator or use an exception reporting tool such as Rollbar. Wondering what approach you take. Maybe I'm missing something obvious.

**Comment by amro** [comment]
It depends™ but put another way, you're asking how to keep track of an asynchronous job's state. How you do that depends on how you're tracking queued jobs. If you're keeping track of the job in the DB, then you can update the row and set the error there.

So the flow might be something like this:
1) User clicks button to do something
2) You show a spinner while you queue the job
3) The job runs and succeeds or fails - you set that state on the row for the job in your data store
4) The client is alerted (either by polling via an an async http request, which is simpler, or via a message that comes back over a socket connection) to the new state and updates the UI to show success or failure

The Active Job docs talk about `after_perform`, which might be the right place to update your job record.

This is more general than Gibbon and not trivial to set up.

It's worth asking yourself in what cases is it worth handling errors? If it's a fire and forget subscription then it may not be not worth handling it -- the user has moved on. But if it's important to capture every email subscription, then you can just make the request to MailChimp's API synchronously (i.e. not in a job) so you can render the response as soon as the API request is completed. In this case, you would want to set a low timeout -- maybe 5 seconds.

Another example: If your app integrates with MailChimp to do something like sync emails between its own DB and MailChimp then errors are probably very important. In that case, it's worth building a system that reports errors and tries to resolve them, and perhaps reports them to you or the user on some error page later if it cannot.

Hope that helps!

**Comment by DanielKehoe** [comment]
Thanks!
