### ISSUE TITLE
Gibbon::MailChimpError: the server responded with status 400

### ISSUE THREAD

**Issue by DanielKehoe** [amro/gibbon#133]
I'm trying to convert code from Gibbon 1.0 to 2.0.

I've got a user model with a method:
```
 def subscribe
    mailchimp = Gibbon::API.new(Rails.application.secrets.mailchimp_api_key)
    result = mailchimp.lists.subscribe({
      :id => Rails.application.secrets.mailchimp_list_id,
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end
```

I tried:
```
  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    result = mailchimp.lists(Rails.application.secrets.mailchimp_list_id).members.create(body:{
      email_address: self.email,
      status: 'subscribed'
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end
```

I got:
```
Gibbon::MailChimpError: the server responded with status 400
```

Also, how do I specify double_optin, update_existing, and send_welcome? I can't find a reference to any equivalents in the MailChimp 3.0 API docs.

Thanks!

**Comment by amro** [comment]
I think http 400 usually means the member is already subscribed.

Look at the JSON schema file for a list member to see the other available parameter names. The doc is sort of buried in the schema now but it's nice in that one could generate code to target it, if they so desired.

Thanks,
Amro

**Comment by amro** [comment]
Now that I'm back at my machine, here's the [JSON schema](https://us9.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json) for list member. I don't see options for double opt-in, update_existing, or send_welcome though. I'd contact MailChimp support to see if these features are documented elsewhere or will be added to the API later.

Sorry I can't be more helpful here but I just don't know the answer.

**Comment by DanielKehoe** [comment]
Thanks! I've queried MailChimp support and I'll post the answer here when I get it:
```
I've been using the MailChimp 2.0 API (with the Ruby Gibbon gem). When I subscribe a member to a list, I specify double_optin, update_existing, and send_welcome parameters. I've looked at the new MailChimp 3.0 API, specifically the JSON schema for list member. But I don't see options for double_optin, update_existing, and send_welcome parameters. What happened to these options? Can I set these options with the MailChimp 3.0 API?
```

**Comment by DanielKehoe** [comment]
Here's the reply I received from MailChimp support:

With API v3.0, subscribers can be set to single or double opt-in using the status field to specify subscribed (single) or pending (double). There's a bit of information regarding this here: http://kb.mailchimp.com/api/article/how-to-manage-subscribers

Currenlty the option to enable the final welcome email with 3.0 will need to be enabled directly through the app list settings (lists--> settings--> list name & defaults). With this enabled, the final welcome email will send to those double opt-in subscribers. 

Lastly, in order to update a subscriber through the API, the PATCH request can be made to update that subscriber. The above link also contains additional information on updating an address.

**Comment by amro** [comment]
Great. FYI: Calling `update` when making a request with Gibbon maps to HTTP PATCH.

**Comment by DanielKehoe** [comment]
I'm trying to diagnose the reason I'm getting ```Gibbon::MailChimpError: the server responded with status 400``. I'm catching the exception and writing to the log:
```
    begin
      result = mailchimp.lists(some_id).members.create(body:{
        email_address: user.email,
        status: 'subscribed'
      })
    rescue Gibbon::MailChimpError => exception
      Rails.logger.error("failed becuz #{exception.detail}")
    end
```
And the error message in the log file is not helpful:
```
failed becuz The resource submitted could not be validated. For field-specific details, see the 'errors' array. 
```
Is the errors array available through an ```exception``` method? What method reveals it?

**Comment by amro** [comment]
Try error.body and error.raw_body

https://github.com/amro/gibbon/blob/master/lib/gibbon/mailchimp_error.rb

Thanks,
Amro
