### ISSUE TITLE
Are 'Interests' the same as 'groupings'?

### ISSUE THREAD

**Issue by DanielKehoe** [amro/gibbon#134]
The README file has an example of subscribing a member to a list with specific interests. However, I am  confused by the terminology "interests." The MailChimp support document [About Segments and Groups](http://kb.mailchimp.com/segments/about-segments-and-groups) describes segments and groups. The [JSON schema](https://us9.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json) for List Members includes "Interests." Do you know whether this refers to Segments or Groups?

I've got Gibbon 2.0 code that looks like this:
```
      merge_fields: {:NAME => user.name,
                      :groupings => [{:name => 'AFFILIATION',
                                      :groups => ['some_list_group']
                                     }]
```
Does this get replaced by interests?

**Comment by DanielKehoe** [comment]
I asked MailChimp support to clarify. Here's what they said:

 Interests in API 3.0 are Group Names in your List (the subgroups), and Categories are the Group Titles. Just like back in API 2.0 with Interest Groupings: 

[/lists/interest-groupings.format -v2.0](https://apidocs.mailchimp.com/api/2.0/lists/interest-groupings.php)

For example, if I have a Group Title Ice Cream Flavors and two Group Names Chocolate and Birthday Cake, that would mean that Ice Cream Flavors is the category for my API call, and Chocolate would be one of the interests.

We have some documentation that can help explain here:

[List Interest Categories Instance](http://kb.mailchimp.com/api/resources/lists/interest-categories/lists-interest-categories-instance)
[List Interests Instance](http://kb.mailchimp.com/api/resources/lists/interest-categories/interests/lists-interest-groups-instance)

**Comment by amro** [comment]
Yes. Interests is short for interest groups.

Thanks,
Amro

**Comment by amro** [comment]
Thanks for posting their response
