### ISSUE TITLE
How to get list members with "start and limit"

### ISSUE THREAD

**Issue by microdevil** [amro/gibbon#136]
Before i was updating gibbon version, i could get my member in mailchimp that supporting pagination using this code

*gb.lists.list({:start => 0, :limit=> 100})*

However with the latest version, i could not get the example how i get my member in mailchimp with pagination format.

This is my code today 

*gb.lists(LIST_ID).members.retrieve*

Could you give me an example or documentation to fix my problem ?

Thanks

**Comment by amro** [comment]
Hi @microdevil, MailChimp has documentation on [Pagination (and more)](http://kb.mailchimp.com/api/article/api-3-overview) in API v3 that you can review at your leisure.

And I have an example of passing parameters in the README (that example happens to be for lists). Putting it all together, something like this should work for you:

    gibbon.lists(list_id).members.retrieve(params: {offset: 0, count: 100})
