### ISSUE TITLE
Creating campaigns

### ISSUE THREAD

**Issue by hydrozen** [amro/gibbon#138]
Do you have any examples on how to create a campaign through the 3.0 API? I can’t find the information in the documentation of mailchimp :(

**Comment by amro** [comment]
Hi Patrick, It looks like MailChimp API v3 does not (yet?) support campaign creation. You can drop down to Gibbon 1.x, which hits API v2, but I believe campaign creation on API v2 is limited to old campaigns and not the new drag and drop campaigns.

I suggest contacting their support folks directly to see if support for campaign creation is planned. Sorry I can't help more on this one.
