### ISSUE TITLE
Mailchimp Export API available in Gibbon v2.0.0?

### ISSUE THREAD

**Issue by analyticsPierce** [amro/gibbon#139]
With Gibbon versions 1.2.0 and prior (with Ruby 2.2.0) I could connect to the Export API with:

`@gibbon_export = Gibbon::Export.new(@api_key)`

However, with v2.0.0 when I try to connect with the above I get:

`uninitialized constant Gibbon::Export`

Searching through the repo I found this commit: https://github.com/amro/gibbon/commit/0fcffa45b371c7bf40b6d23fc5d3149ad0ac1202  which has a 2.0.0 tag and instructions similar to what I have. However, the details for exporting no longer appear in the README. 

Is there a different method to connect to the Export API with Gibbon v2?

**Comment by amro** [comment]
Hi Jason. Gibbon 2.x targets MailChimp API v3, which does not have an export API. It does, however, support pagination. If you need to export mass data, then you should stick to Gibbon 1.x, which targets MailChimp API v2.

**Comment by analyticsPierce** [comment]
Ah ok. From the Mailchimp docs (https://apidocs.mailchimp.com/export/1.0/), it looks like the Export API is separate and on its on version that was different from the Mailchimp API. Maybe I am misunderstanding.

I'm wondering if you have plans to include support for Export API v1 along with Mailchimp API v3 at some point? Or will Export API stay tied to Mailchimp API v2 in Gibbon? 

Curious as I need to support Mailchimp API v3 and Export API v1 currently.

**Comment by amro** [comment]
Or maybe I am the one who has misunderstood this! I've always thought to MailChimp API V2, but you're right that it's at a completely different endpoint. For now that functionality is only in Gibbon 1.x.

Let me see about adding this functionality back to Gibbon.

**Comment by analyticsPierce** [comment]
Great. Thanks for taking a look. Let me know if I can help.

**Comment by amro** [comment]
I spent some time on this last night and just pushed it to master. It's not finished - there's some code that could probably be shared between ExportRequest and Request and it needs unit tests and manual testing.

It would be much appreciated if you could help with either of those.

Usage is something like this:

    export = Gibbon::ExportRequest.new(api_key: "yourkey-dc")
    export.list(id: "your-list-id")```

This isn't ideal since it'll return an array of all rows, which will consume a lot of memory for large data sets.

It's better to handle the results as a stream instead of all at once. To do so, pass a block:

    export = Gibbon::ExportRequest.new(api_key: "yourkey-dc")
    export.list(id: "your-list-id") { |row| puts row }

All Export API methods should work but I've only had time to test the `list` call. Note that the Export API returns HTTP 200 in at least some error cases. So I wouldn't rely on the status code. Also, note that you should wrap calls in begin/rescue.

**Comment by amro** [comment]
@analyticsPierce Okay - so actually the Export API is not the way to go. MC apparently launched a Batches endpoint recently. Check out [their playground](https://us1.api.mailchimp.com/playground) to try it out. I suggest digging through the schema - apparently it's asynchronous. I'm going to roll back the commits I made relating to this. (I should have put them on a feature branch - doh).

**Comment by analyticsPierce** [comment]
Did you get any feedback suggesting that Batches would replace Exports? I'm not seeing anything in Batches that looks like it would return campaign activity data (for example). Interesting that Batches do not show up in the API v3 resource: http://kb.mailchimp.com/api/resources. 

Do you want to move those changes over to a feature branch? I am happy to do some work on it if Batches is not supporting the Export API methods.

**Comment by amro** [comment]
Something like that. I expect the resource page to be updated in the near future. I'd ask MailChimp support about how to get campaign activity. Sorry, but I don't know. I do see this in the Batches schema:

```"schema": {
						"type": "string",
						"description": "For HTTP methods that can receive bodies (POST and PUT), this is a URL representing the schema that the body should conform to.",
						"example": "https://us2.api.mailchimp.com/schema/3.0/Lists/Instance.json",
						"links": null
					}```

Which leads me to believe you can pull *any* data for which there's a resource asynchronously via the batch API.

**Comment by analyticsPierce** [comment]
Got some feedback from the Mailchimp API team about Batches. You were correct. Here is their reply:

Batch Operations that we've added in API 3.0 will be taking place of the export API. With the batches, you can specify a series of operations to perform in the initial request, and then wait while we do the heavy lifting. We'll also give you another endpoint to check out, and once we're done, you can grab the full response for the batch there. This guide walks through how to make those requests: http://kb.mailchimp.com/api/article/how-to-use-batch-operations

**Comment by amro** [comment]
Good to know - thanks! I'll add a link to the batch operations article in the README.
