### ISSUE TITLE
double opt-in in version 2

### ISSUE THREAD

**Issue by utiq** [amro/gibbon#140]
How can I activate the double opt-in in version 2

When I do this I don't receive the email:
Gibbon::Request.lists('xxxxxxx').members.create(body: {email_address: params[:email_address], status: "subscribed"})
When I do this the option doesn't exists
Gibbon::Request.lists('xxxxxxx').members.create(body: {email_address: params[:email_address], status: "subscribed"}, :double_optin => true)

**Comment by amro** [comment]
Hi @utiq, MailChimp's API has changed a bit. Check out this [knowledgebase article](http://kb.mailchimp.com/api/article/how-to-manage-subscribers), which they put up. In short, instead of `subscribed`, you should pass `pending`.
