### ISSUE TITLE
member-info call not working

### ISSUE THREAD

**Issue by teylewr** [amro/gibbon#141]
Wondering if there is a way to get member-info call to work.  Need a good way to check if member exists in a list by email string, so i can know if i need to update or add. Pulling entire list to check 10-50 at a time isnt very efficient.

https://apidocs.mailchimp.com/api/2.0/lists/member-info.php

**Comment by amro** [comment]
If you're using MC API 2 (i.e. Gibbon 1.x) then there's an update_existing flag you can pass when subscribing a list member. That would save the need for a check.

If you're using MC API 3 (i.e. Gibbon 2.x) then it's a bit different. I'd check MailChimp's documentation. Off hand, I know the API returns an error if the member is already subscribed. So you could optimistically subscribe and only update if the subscription call fails, which saves you a call in the case where the list member is new to your list.

What version of Gibbon are you using?

**Comment by teylewr** [comment]
Using gibbon 2.x
Thought about trying to update but have same need where i dont know the id of the email in list to update until i get it from the list.

**Comment by amro** [comment]
Gibbon 2.x targets API 3, so you're looking at the wrong documentation all together. Please see out the [updated doc](http://kb.mailchimp.com/api/). API 3 is very different from version 2. Here's the doc on [list member instance](http://kb.mailchimp.com/api/resources/lists/members/lists-members-instance). I think you can attempt to fetch the list member by computing the member's ID. It's just the md5 hash of the lowercase email address. I'm sure you have seen them but I also have some examples of subscribing a list member in Gibbon's README.

**Comment by teylewr** [comment]
Oh gosh, somehow missed that. Yeah I think that solution works then. Sorry about that.

**Comment by amro** [comment]
No problem!
