### ISSUE TITLE
Query API

### ISSUE THREAD

**Issue by stephanemaarek** [amro/gibbon#143]
Hi,

I'd like to query mailchimp for a specific email address. I'm doing this but it's not working:

```
          members_match = gibbon.lists(list_id).members.retrieve(params: {email_address: member[:email] })["members"]
```

Am I doing something wrong ?

Thanks!
Stephane

**Comment by amro** [comment]
According to MailChimp's docs, that should return the first 10 members. I don't know what passing email_address to that call does (if anything).

I suggest looking at the [List Members Instance](http://kb.mailchimp.com/api/resources/lists/members/lists-members-instance) doc instead. There you can see that you can see that one can fetch a specific member by email address. You need to hash the lower cased email address. With Gibbon, I think that would look like this:

    email_hash = <email address lowercased, trimmed, and md5 hashed>
    gibbon.lists(list_id).members(email_hash).retrieve

You should always wrap calls in a begin/rescue so you can handle errors returned by the API.
