### ISSUE TITLE
I have list. I want to subscribe new user if not on list otherwise leave it be.

### ISSUE THREAD

**Issue by sulmanhotmail** [amro/gibbon#145]
i am new to ruby on rails.... Please help me... I am using Gibbon 2.x... I have list in mailchimp... I have rails app that call to gibbon subscribe after user is created.... but if the user is already in the list then error comes... please help me in this matter. I want not to run create function if user is already in the mailchimp list.

**Comment by amro** [comment]
Hi @sulmanhotmail. Please see the `upsert` example in the README:

    gibbon.lists(list_id).members(lower_case_md5_hashed_email_address).upsert(body: {email_address: "foo@bar.com", status: "subscribed"})

You still need to wrap the call in a begin/rescue to handle other errors (API errors or timeouts, etc.).

**Comment by sulmanhotmail** [comment]
Thanks solved.... very great problem solver gem for mailchimp is GIBBON.... thanks

**Comment by p29892p** [comment]
Can you post your example of code here. So that i can understand the exact JSON format of the request.
