### ISSUE TITLE
Can't manage to upsert :-/

### ISSUE THREAD

**Issue by sebabouche** [amro/gibbon#146]
Hi,
I'm trying to take advantage from the fabulous **upsert** technique described in the README in a Rails App but with no success so far:

    class SubscribeUserToMailingListJob < ActiveJob::Base
        queue_as :default

        def perform(user)
            begin
                gibbon = Gibbon::Request.new
                member_id = Digest::MD5.hexdigest(user.email.downcase)
                list = ENV["MAILCHIMP_LIST_ID"]
                gibbon.lists(list).members(member_id).upsert(body: {
                                                            email_address: user.email, 
                                                            status: "subscribed",
                                                            double_optin: false,
                                                            merge_fields: {FROM: "Store"} 
                                                          })

              # gibbon.lists(list).members.create(body: {
              #                                           email_address: user.email, 
              #                                           status: "subscribed",
              #                                           double_optin: false,
              #                                           merge_fields: {FROM: "Store"} 
              #                                         })

            rescue Exception => e
                logger.error e.title
                logger.error e.detail
                logger.error e.body
            end
        end
    end

It was working like a charm with create. But I was as expected getting errors when trying to create an already created subscriber.

I've read this issue https://github.com/amro/gibbon/issues/145 and tried to trigger things from the console.

**Comment by amro** [comment]
`double_optin` isn't an option. Try `status: "subscribed"` instead. If that doesn't help, what error are you seeing?

**Comment by sebabouche** [comment]
[ActiveJob] [SubscribeUserToMailingListJob] [b3985dbd-9ed9-4bc8-83f8-f1663ccec488] Performing SubscribeUserToMailingListJob from Inline(default) with arguments: gid://silex/User/9
    [ActiveJob] [SubscribeUserToMailingListJob] [b3985dbd-9ed9-4bc8-83f8-f1663ccec488] Performed SubscribeUserToMailingListJob from Inline(default) in 1.25ms

**Comment by amro** [comment]
Did you change the parameter, as I suggested? double_optin isn't a valid parameter in API v3, if I'm not mistaken.

**Comment by sebabouche** [comment]
Yes I got rid of it.

**Comment by amro** [comment]
But did you add the status? It might be required. I could be wrong.

**Comment by sebabouche** [comment]
Yes it was there already:
      gibbon.lists(list).members(member_id).upsert(body: {
                                                            email_address: user.email, 
                                                            status: "subscribed",
                                                            merge_fields: {FROM: "Store"} 
                                                          })

**Comment by amro** [comment]
Ah, I see

**Comment by sebabouche** [comment]
irb(main):033:0> begin
    irb(main):034:1* gibbon.lists(list).members(member_id).upsert(body: {email_address: "sebastien@nicolaidis.org", status: "subscribed",merge_fields: {FROM: "Store"}})
    irb(main):035:1> rescue Exception => e
    irb(main):036:1> puts e
    irb(main):037:1> end
    => #<Gibbon::Request:0x007fb601005b68 @path_parts=["lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "upsert", {:body=>{:email_address=>"sebastien@nicolaidis.org", :status=>"subscribed", :merge_fields=>{:FROM=>"Store"}}}], @api_key="e31e8addf06ad5b6594534d7227a04c3-us11", @api_endpoint=nil, @timeout=15>
    irb(main):038:0>

**Comment by sebabouche** [comment]
<img width="1340" alt="capture d ecran 2015-10-20 a 19 03 10" src="https://cloud.githubusercontent.com/assets/6465147/10614938/42307304-775d-11e5-8721-7eac9e479bb1.png">

**Comment by amro** [comment]
Very strange. I've just tried it and it worked fine. Try printing e.raw_body, though I'm not sure it'll help since it just printed the request instance.

    gibbon.lists("31067f2f53").members("d425e....").upsert(body:{email_address: "...", status: "subscribed", merge_fields:{LNAME: "foo"}})
    => {"id"=>"d425e8e26683ca2b40f729d5db537442", ...}

**Comment by sebabouche** [comment]
=> #<Gibbon::Request:0x007fb601005b68 @path_parts=["lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "upsert", {:body=>{:email_address=>"sebastien@nicolaidis.org", :status=>"subscribed", :merge_fields=>{:FROM=>"Store"}}}, "lists", "915e2a2b33", "members", "88f68bebda8e1b1ebce253f6a148b82f", "upsert", {:body=>{:email_address=>"sebastien@nicolaidis.org", :status=>"subscribed", :merge_fields=>{:FROM=>"Store"}}}], @api_key="e31e8addf06ad5b6594534d7227a04c3-us11", @api_endpoint=nil, @timeout=15>

Here is the e.raw_body (and then this is a real error, my mistake ^^).

**Comment by sebabouche** [comment]
Isn't it weird that it is repating the path so much?

**Comment by amro** [comment]
Actually, I think I know what's happening. Upsert was added in Gibbon 2.1.0. I attempt to version Gibbon based on semantic versioning so you might not have upgraded from 2.0.0.

**Comment by sebabouche** [comment]
You were right. Bundle update gibbon. And everything works like expected. What a shame, thank you so much for your time. Hope this will help others ;-)

**Comment by amro** [comment]
Glad it's working. :)

**Comment by whomwah** [comment]
+1 to @amro. Had the same issue as @sebabouche and had ```gem 'gibbon', '~> 2.0.0'``` in Gemfile.

**Comment by fltiago** [comment]
:+1: to @sebabouche. @amro is there any way to avoid this strange behaviour? In 2.0.0 version the request isn't even send. I can implement if you want to, just give me some clue how to do it.

**Comment by amro** [comment]
This is a feature that was added in 2.1. I'm not sure why that is considered strange. I think I should update the README to explain 2.1 is required for upsert support. I'll do so since it's tripped up a few folks - sorry about that.

**Comment by amro** [comment]
@fltiago After rereading, I understand what you mean now. The issue is Gibbon 2 uses the builder pattern. The verbs are essentially treated as terminators (i.e. they trigger the request) so 2.0.0 treated upsert as just another part of the path it constructed since it wasn't defined in that version.

I'm not sure how to avoid this other than hard coding every potential path and that's exactly how I don't want to build gibbon. I'm open to ideas though. :)
