### ISSUE TITLE
Retrieve Member by unique_email_id? 

### ISSUE THREAD

**Issue by stevebenjamins** [amro/gibbon#147]
Hi,

I'm successfully retrieving members by their email address:

`member_id = Digest::MD5.hexdigest("email@gmail.com")`
`gb.lists(list_id).members(member_id).retrieve`

But I'm wondering if it's possible to retrieve a member by their unique_email_id (as set by Mailchimp)? 

Gibbon has been really helpful so far— thanks!

**Comment by amro** [comment]
I'm sorry, but I don't know the answer to this one. I suggest asking MailChimp's API team whether you can fetch an email by unique_email_id. If it's possible to do with the API, it should be possible to make the request to Gibbon without any special support from me.

**Comment by amro** [comment]
I'd appreciate it if you reported their response here, when you can. If it's possible, I'll add a note to the README.

**Comment by stevebenjamins** [comment]
Awesome, thank you. I'll ask the support team and post back here!
