### ISSUE TITLE
undefined method `api_key=' for Gibbon:Module (NoMethodError)

### ISSUE THREAD

**Issue by wraithseeker** [amro/gibbon#148]
In my gemfile
`gem 'gibbon'`

Gibbon file

`Gibbon.api_key = "someapikey"`
`Gibbon.timeout = 15`
`Gibbon.throws_exceptions = false`

I am receiving an error when trying to create an ActiveJob to use with Gibbon with the following command `bin/rails generate job subscribe_user_to_mailing_list` using the tutorial http://aspiringwebdev.com/e-mail-in-rails-with-mailchimp-and-mandrill-a-comprehensive-guide/

Error
/Users/wraithseeker/Desktop/app/config/initializers/gibbon.rb:6:in `<top (required)>': undefined method `api_key=' for Gibbon:Module (NoMethodError)

**Comment by amro** [comment]
Please see the README:
    Gibbon::Request.api_key = "your_api_key"
    Gibbon::Request.timeout = 15
    ...
