### ISSUE TITLE
Create and send campaigns?

### ISSUE THREAD

**Issue by kt-jet** [amro/gibbon#150]
Is it also possible to create and send off a campaign through the gibbon gem?
And if yes, what should that process roughly look like?

Bg:
I need to send an email to all users every day (yes, they want it that way :-)
The mail campaign can use a standard template that I create in Mailchimp. I would need to fill in some content from my Rails app and send it off, lets say every day at six o'clock.

**Comment by amro** [comment]
Hi @kt-jet, Not with Gibbon 2.x, which targets MailChimp API 3. You can see that there's currently no create support in MailChimp API 3 in the API [documentation](http://kb.mailchimp.com/api/resources/campaigns/campaigns-collection).

If you use Gibbon 1.x, which targets MailChimp API 2, then you can create campaigns but usage is different so check the [README for that version of the gem](https://github.com/amro/gibbon/tree/api_v2) and MailChimp's corresponding [API documentation](https://apidocs.mailchimp.com).

**Comment by q3-tech** [comment]
@amro 
The documentation specifies a create support for campaigns creations.
I tried creating a campaign with the following parameters -
`gb.campaigns.create({:type=>"plaintext",
                                    :options =>  {:list_id=>"xxx"}, 
                                    :settings => {:subject_line => "Hello World",
                                                        :reply_to => "shreya@xxx.com", 
                                                        :from_name => "abc",
                                                        :to_name =>"Programmer"}})`

I am getting the following error message - 
`ArgumentError: unknown keywords: type, options, settings`

**Comment by amro** [comment]
Hi Nitin, 

I think your problem is you have not specified how you what gibbon to send those parameters. Try adding "body: " before your hash. It's a named parameter. There is an example of that and more in the README. :)

Also, please make new tickets for questions instead of commenting on old ones.
