### ISSUE TITLE
Retrieving more interests than the default 10 entries MailChimp allows

### ISSUE THREAD

**Issue by kplattret** [amro/gibbon#151]
Hi there, I just talked to MailChimp as I was experiencing an issue retrieving all the interests from a given interest category. I have 11 interests and it appears that the API only returns the first 10 by default and that's exactly what happens when I use the following call:

```ruby
g = Gibbon::Request.new
g.lists(list_id).interest_categories("0ace7aa498").interests.retrieve
```

MailChimp said that I could achieve this by adding a 'count' parameter to my API call (`?count=11`). Could you please let me know if that's possible to do using Gibbon?

**Comment by amro** [comment]
Hi @kplattret. Try

    g = Gibbon::Request.new
    g.lists(list_id).interest_categories("0ace7aa498").interests.retrieve(params: {"count": 11})

There are more examples in the [README](http://github.com/amro/gibbon) in case you need to pass headers, etc.

**Comment by kplattret** [comment]
That works a treat! I could probably have figured that out from your documentation indeed.

Thanks for your help @amro.

**Comment by amro** [comment]
No problem at all. There's plenty that I'm sure I've left out of the doc. Let me know if you run into any other trouble. :)
