### ISSUE TITLE
NoMethodError: undefined method message= for Gibbon::MailChimpError

### ISSUE THREAD

**Issue by shayfrendt** [amro/gibbon#154]
This is happening when a `Faraday::Error::ClientError` gets raised with response values:

```
#<NoMethodError: undefined method `message=' for #<Gibbon::MailChimpError: the server responded with status 503>
```

It appears to be hitting [this line](https://github.com/amro/gibbon/blob/439a321bea4abb08c6e9de16f6cbecfa110e69c5/lib/gibbon/api_request.rb#L109) in the rescue block, which calls a method on the `MailChimpError` class that doesn't exist.

**Comment by amro** [comment]
First, thanks for the PR, but I'm not yet certain adding message is the thing to do here. I think there needs to be better error handling around pulling response values out of `error` in `handle_error()`. I'm also not sure stomping over the fields in that rescue block, as I have done, is a good idea.

So I'd like a little more information, if possible. Do you have the full stack trace? I'm most interested in what line in `handle_error()` the code is failing.

Finally, sorry for any trouble this has caused you.

**Comment by amro** [comment]
Actually, I'm wrong! Adding `message=` is useful here. But I'd still like to have better error handling in `handle_error()`. Can you provide the stack trace anyway?

**Comment by shayfrendt** [comment]
Sure thing - here's the backtrace:

```
vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:96:in `rescue in handle_error'
vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:80:in `handle_error'
vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:29:in `rescue in patch'
vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:23:in `patch'
vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/request.rb:34:in `update'
```

**Comment by amro** [comment]
I'm going to release a point release now since this will solve the problem in the short term, but I'm still not clear on what triggers the failure to begin with. The stack trace you posted shows the failure on line 93, which is a begin statement. The prior version, which I received via email was:

    vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:96:in `rescue in handle_error'
    vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:80:in `handle_error'
    vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:29:in `rescue in patch'
    vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:23:in `patch'
    vendor/gems/2.1.7/ruby/2.1.0/gems/gibbon-2.0.0/lib/gibbon/request.rb:34:in `update' 

Which shows line 96 as the problem:

    if error.is_a?(Faraday::Error::ClientError) && error.response

So `error.response` throws an exception? That's strange. Is there more to the back trace?

Thanks @shayfrendt.

**Comment by amro** [comment]
I've released v2.1.1 so you and others don't run into the larger problem here. If you can spare a few minutes to help me find the actual problem, I would sincerely appreciate it. I can release another update later tonight if we can solve this before then.

**Comment by shayfrendt** [comment]
@amro I'd updated that stack trace because the one I'd sent was for `gibbon-2.0.0` instead of `gibbon-2.1.0` (check the vendor/gems path there).

***

I believe Faraday includes the [response values](https://github.com/lostisland/faraday/blob/5bfa4bf9480f18bed0d4fe721ebb370cf7cae92e/lib/faraday/response/raise_error.rb#L13) if there are client error statuses, so this must be a case of where those response values can't be parsed by Gibbon for whatever reason.

**Comment by shayfrendt** [comment]
>Just giving me a way to reproduce this is enough. i.e. What command are you running that is failing? I'll try it against my account and figure it out.

@amro Other than including the unparseable `body` in [this test line](https://github.com/amro/gibbon/blob/cd5db98c6801971e7cd3ae23de39e3cb674a4047/spec/gibbon/api_request_spec.rb#L26), which is how I replicated the error in test, I'm not sure. I'm seeing a problem with 503s coming back from Mailchimp right now and am still working through to the root issue with them - I think they may be sending back an invalid body or something, which is what bubbled this up in the first place.

**Comment by shayfrendt** [comment]
Also, thanks for the `v2.1.1` release! :heart:

**Comment by shayfrendt** [comment]
And more context, I was hitting this calls to both `update` and `upsert`.

**Comment by amro** [comment]
Thank you, that helps!

Thanks,
Amro

**Comment by amro** [comment]
Closing this for now. Please let me know if MailChimp lets you know there was an issue on their end. :)

**Comment by shayfrendt** [comment]
>Please let me know if MailChimp lets you know there was an issue on their end.

Mailchimp did confirm that there was an Akamai caching configuration/timing issue related to triggering an automation workflow through the API:

- When you add a subscriber to an automation queue via an HTTP post to `/automations/{workflow_id}/emails/{workflow_email_id}/queue`, the successful response is an HTTP 204 No Content
- If you post again to that same endpoint too quickly, it produces a HTTP 503 response due to attempting to pull the cached 204 No Content data

I don't have a great understanding of how this error scenario is actually possible from a request/response flow standpoint, but I've asked for more clarification from Mailchimp.

**Comment by amro** [comment]
I see. Thanks for the update. :+1:
