### ISSUE TITLE
Upsert producing 400 error

### ISSUE THREAD

**Issue by astjohn** [amro/gibbon#157]
Thanks for this great library. I keep running into `Gibbon::MailChimpError: the server responded with status 400`. I read a past issue that stated this might occur for existing email addresses. To combat this, I've attempted to use upsert.

```
subscriber_hash = Digest::MD5.hexdigest("abc123@gmail.com")
params = {:status=>"subscribe", :language=>"en", :email_address=>"abc123@gmail.com", :merge_fields=>{:FNAME=>"Jimmy", :LNAME=>"Bean"}}

gibbon.lists("abc123").members(subscriber_hash).upsert(body: params)
=>
Gibbon::MailChimpError: the server responded with status 400
```

The error is produced whether the email exists or not in the list. I've replaced the list_id from the actual in the example above. 

Your help is greatly appreciated.

**Comment by amro** [comment]
Hi Adam. I assume you're using Gibbon 2.1.x. The only thing I see wrong, off hand, is the `status` should be "subscribed" as in the past tense of subscribe. Can you try that, please?

Also, you should lower case the email in question before hashing it. I know that doesn't matter in your example, but it could bite you in your real code. :)

**Comment by amro** [comment]
One more thing, you should try catching the error and printing out the [`raw_body`](https://github.com/amro/gibbon/blob/master/lib/gibbon/mailchimp_error.rb) field to see the exact issue.

**Comment by astjohn** [comment]
Damn. The subscribed typo was exactly it. Guess it was a long day. Sorry! Good point about the downcase. We have that in the real code block. Thanks again!

**Comment by amro** [comment]
Glad it worked!
