### ISSUE TITLE
403 Error in Production on Heroku, No Error Message

### ISSUE THREAD

**Issue by travisjtodd** [amro/gibbon#165]
I'm trying to determine if this is a Gibbon problem or a Heroku one. My upsert code is working fine in development, locally and in the remote heroku rails console. It's only failing in my controller and with a very unhelpful error message.

Here is the controller code (list_id and API Key removed):

```
  def subscribe
    gibbon = Gibbon::Request.new(api_key: "[API KEY]")
    # newsletter list: a2308943f1
    gibbon.lists('abcdefg12345').members(Digest::MD5.hexdigest(params["email"]["email"])).upsert(body: {
      email_address: params["email"]["email"], 
      status: "subscribed"
    })

    respond_to do |format|
      format.html
      format.js
    end 

  rescue Gibbon::MailChimpError => error
    @error = {
      title: error.title, 
      detail: error.detail, 
      body: error.body, 
      raw_body: error.raw_body, 
      status_code: error.status_code
    }

    logger.info('Error saving email:')
    logger.info(@error.inspect)

    respond_to do |format|
      format.html
      format.js
    end 

  end
```

And here's the console output (cleaned of timestamps and ip addresses):

```
app[web.1]: Started POST "/mailchimp/subscribe"
app[web.1]: Completed 200 OK in 25ms (Views: 0.9ms | ActiveRecord: 0.0ms)
app[web.1]: Processing by MailchimpController#subscribe as JS
app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"nMaj0GAxGCneJySytVx65S8gScXq+li6IV5QbfRsLsA=", "email"=>{"email"=>"travis@example.com"}, "commit"=>"Keep me updated"}
app[web.1]: Error saving email:
app[web.1]: {:title=>nil, :detail=>nil, :body=>nil, :raw_body=>nil, :status_code=>403}
app[web.1]:   Rendered mailchimp/subscribe.js.erb (0.1ms)
```

As you can see the captured error contains no information. Should I be looking at heroku for why it isn't working or is there something I forgot to do with Gibbon to get it working in production?

Thanks in advance.

**Comment by amro** [comment]
Hmm, that is definitely not a super helpful response.

First q but probably not the issue: Is the email address lower cased before being MD5'd? i.e. Are you entering it in lower case? It needs to be per MailChimp's API docs.

More likely the issue: I looked at [MailChimp's API Error docs](http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/) and they say a 403 is forbidden. So how are you passing in the key? Is it set via an environment variable? Can you print it ahead of time to make sure it's available as expected?

Another thought is to make some other, less complicated, request like `gibbon.lists.retrieve` to see if that succeeds.

**Comment by travisjtodd** [comment]
Thanks @amro I'm being a bit of a bad boy at the moment for testing purposes and the API key is hardcoded into where it says [API KEY]. So, I can't imagine that is the issue, unless it expects an ENV variable?

Email was entered all lowercase. Thanks for the tip though. I added a `downcase` method where necessary. 

`gibbon.lists.retrieve` seemed to work just fine.

... Although, now that I've reverted and pushed everything is working! Perhaps a server restart was just in order. Typical. Thanks, regardless!

**Comment by amro** [comment]
FYI: Another developer reported MailChimp having caching issues w/ their CDN. I don't know if that's the case here or not. Glad it's working.

**Comment by travisjtodd** [comment]
Thanks again for the great gem and excellent support!

**Comment by daveespo** [comment]
FWIW, Heroku dynos have been unable to reliably access the MC API since somewhere around November 16. This is due to a change that MC instituted to block traffic from a malicious user originating from Heroku

The body of the response looks like

````
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;us6&#46;api&#46;mailchimp&#46;com&#47;1&#46;3&#47;&#63;" on this server.<P>
Reference&#32;&#35;18&#46;622f0660&#46;1449030100&#46;112b2bb
</BODY>
</HTML>
````

The only way around the problem is to restart your Heroku dyno(s) and hope that you get launched on an EC2 instance that has a clean IP

There's an unfortunate finger pointing contest between Heroku and Mailchimp right now .. it's amazing that after 2 weeks they can't resolve the problem

**Comment by amro** [comment]
This is unfortunate. I've heard that sending email from EC2, in general, is problematic. I once had the pleasure of working MailChimp so it's easy for me to see their perspective. If they're not careful in handling abuse, then their IPs are blacklisted and their deliverability is negatively impacted. They take this very seriously (and I don't blame them!).

It stinks that devs are caught in the middle of it. I'm sorry to hear it.
