### ISSUE TITLE
Add support for setting proxy config to Gibbon::API (v1) on initialization

### ISSUE THREAD

**Issue by brettfishman** [amro/gibbon#166]
Hello,

I'm wondering if you'd be open to a PR which adds support for passing proxy configuration to Gibbon::API on initialization? We are still on v1.x of Gibbon (Mailchimp's v2 API), and I know you added support for this in v2.x of Gibbon (Mailchimp v3). I also realize Gibbon v1 is being deprecated, so no worries if you'd rather not. I can fork for now, until we migrate to Gibbon v2.

Thanks for your consideration.

**Comment by amro** [comment]
Hi @brettfishman. It's true that Gibbon 1.x is deprecated and it's my hope that it will not need any updates outside of critical bug fixes at this point. I'd prefer if you fork v1 for your own use until you can migrate to v2.

I do have a little section about migrating from v1 to v2 at the bottom of v2's readme that I hope you'll find helpful. But please feel free to open an issue for questions you have while you're migrating and I'll do my best to answer them[1]. Unless you're making very heavy use of MailChimp's API, I think you'll find migration to be pretty straight forward. MailChimp's new API is pretty nice, IMO. :+1: 

[1] Sometimes I don't know the answer to API specific questions and will direct you to MailChimp support.

**Comment by brettfishman** [comment]
@amro No problem - I've already forked v1 and have it working as I'd like. And yes, migrating to v2 is on our radar. Good to hear you think well of MailChimp's new API. 

I'll close this issue. Thanks.

**Comment by amro** [comment]
Thanks for understanding

**Comment by rochers** [comment]
@brettfishman Is your fork public? Can you provide a link to it?
