### ISSUE TITLE
No Error Message

### ISSUE THREAD

**Issue by adrianoresende** [amro/gibbon#167]
I have same problem https://github.com/amro/gibbon/issues/165 but in development.
My code work fine, 

initializers/gibbon.rb (API_KEY in xxx)
```ruby
Gibbon::Request.api_key = 'xxx'
Gibbon::Request.timeout = 15
```

Controller (LIST in xxx)
```ruby
def mailchimp

    list_launch = 'xxx'
    g = Gibbon::Request.new

    begin
        @response = g.lists(list_launch).members.create(body: { email_address: params[:email] })
    rescue Gibbon::MailChimpError => e
        puts "-------------------------------------"
        puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
        puts "-------------------------------------"
    end

    respond_to do |format|
       format.js
    end

  end
```

Console output (error empty)
```
Started POST "/mailchimp" for ::1 at 2015-12-16 01:53:41 -0200
Processing by PagesController#mailchimp as JS
  Parameters: {"utf8"=>"✓", "email"=>"zullcore@gmail.com"}
-------------------------------------
Houston, we have a problem:  - 
-------------------------------------
  Rendered pages/mailchimp.js.erb (0.1ms)
Completed 200 OK in 717ms (Views: 39.5ms | ActiveRecord: 0.0ms)
```

Error contains no information, i not know best way to check this error, someone knows how to solve?

**Comment by amro** [comment]
Are you also using Heroku?

**Comment by adrianoresende** [comment]
Log `e`
`SL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

Log `inspect`
`#<Gibbon::MailChimpError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed>`

This problem SSL in development is very headache. =/

**Comment by adrianoresende** [comment]
I solved SSL with this code:
`OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE`

Now another error is status 400
```
the server responded with status 400
#<Gibbon::MailChimpError: the server responded with status 400>
```

**Comment by mameier** [comment]
Instread of overwriting a global "constant" for all your project, I prefer to temporarily set SSL_Check to false.
Since Gibbon uses Faraday, I wrap my client calls in 
>  Faraday.default_connection_options[:ssl] = Faraday::SSLOptions.new(false) 
> clinet....
> Faraday.default_connection_options[:ssl] = nil

And all that is only nescessary because some mailchimp servers have broken SSL chains. See for example https://www.sslshopper.com/ssl-checker.html#hostname=us12.api.mailchimp.com.

I have to do this hack also in production until mailchimp solves this problem, that is reported for over 4 weeks now.

**Comment by amro** [comment]
I'm going to close this since it's not a Gibbon specific issue. I hope it's resolved very soon.

**Comment by amro** [comment]
I thought of one thing: I noticed your log mentions SSL v3. I wonder if that's disabled on MailChimp's end since it's known to be insecure. Is you machine up to date?

**Comment by amro** [comment]
Yes, MailChimp only supports TLS. I suggest starting your troubleshooting there.

**Comment by fltiago** [comment]
@amro how can I set gibbon to use TLS instead of SSL?

Thanks, for any help.

**Comment by amro** [comment]
This is a configuration issue on your machine so I'm candidly not sure. I would expect it to happen  happen by default. I think I would start by making sure Ruby and OpenSSL were up to date.

**Comment by fltiago** [comment]
@amro thanks for your answer, I didn't solve the problem yet, I just set to not use SSL in development. In production probably is gonna work.

**Comment by amro** [comment]
@fltiago Please see https://github.com/amro/gibbon/issues/173 and try my suggestion. Let's continue the conversation there.
