### ISSUE TITLE
Sidekiq can't retry the job when MailChimpError exception was raised

### ISSUE THREAD

**Issue by freemanoid** [amro/gibbon#170]
When Gibbon throws `MailChimpError`, sidekiq can't retry the job, because `message` instance variable of the exception is `nil`.
Instance variable `message`  is used by `StandardError` for the error message which is passed by initializer like this `StandardError.new("error message")`. 
Here is the place where `message` is overriden https://github.com/amro/gibbon/blob/master/lib/gibbon/mailchimp_error.rb#L3

**Comment by amro** [comment]
Thanks again for fixing this
