### ISSUE TITLE
Gibbon not working for ruby  2.2.3

### ISSUE THREAD

**Issue by preety-singal** [amro/gibbon#173]
While subscribing new users it throws the error SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil

**Comment by amro** [comment]
Please see this [Faraday doc](https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates) on SSL. In particular, please try exporting the export `SSL_CERT_FILE` environment variable.

MailChimp doesn't support SSL v3. I'm not sure why it's being attempted here though at least one other person has run into this. Please try that environment variable (details in the doc I linked to above) and let me know if it fixes your problem.

**Comment by fltiago** [comment]
@amro thanks, I will take a look and try your suggestion.

**Comment by heathered** [comment]
@amro That worked for me, thanks!

**Comment by amro** [comment]
@heathered great! Glad to hear that.

**Comment by dwkns** [comment]
Assuming you are using Homebrew and RVM...

Some versions of the available binaries supplied by RVM assume the location of your SSL certificates. And on occasion even exporting the `SSL_CERT_FILE` doesn't work.

This can be solved by compiling a version of Ruby locally rather than depending on the RVM suppled binaries. So...

    $ rvm install ruby <ruby-version> --disable-binary

It takes a bit longer but avoids the SSL issues that can arise.

**Comment by tboyko** [comment]
Can't seem to get it to work even when specifying the cert path in ruby:

    f = Faraday.new("https://us6.api.mailchimp.com", :ssl => { :ca_path => "/usr/lib/ssl/certs" })
    f.get '/' # raises error

I also tried defining `SSL_CERT_FILE` in `/etc/environment` but had the same issue after restarting apache. Worth noting is that I'm using Phusion Passenger.

Is it possible that my ssl certs are out of date?

**Comment by amro** [comment]
@tboyko Faraday's doc shows a path to a specific CA cert file, not a path to where all of your certs live. I think that's causing your problem.

    export SSL_CERT_FILE=/usr/lib/ssl/certs/ca-certificates.crt

**Comment by tboyko** [comment]
Noticed and tried that as well. I should have noted that.

**Comment by argent-smith** [comment]
@amro export SSL_CERT_FILE=/usr/lib/ssl/certs/ca-certificates.crt doesn’t work. 

```
root@fecfc0f2e9ee:/usr/src/app# rails c
Loading development environment (Rails 4.2.5)
[1] pry(main)> ENV[‘SSL_CERT_FILE’]
=> "/usr/lib/ssl/certs/ca-certificates.crt"
[2] pry(main)> g = Gibbon::Request.new
=> #<Gibbon::Request:0x005604f26ae670
 @api_endpoint=nil,
 @api_key="XXXXXXXXXXXXX",
 @faraday_adapter=:net_http,
 @path_parts=[],
 @proxy=nil,
 @timeout=30>
[3] pry(main)> g.lists.retrieve
Gibbon::MailChimpError: SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil
from /usr/local/bundle/gems/gibbon-2.2.3/lib/gibbon/api_request.rb:120:in `handle_error’
```

**Comment by amro** [comment]
@heathered Can you share how you fixed this in your environment?

**Comment by amro** [comment]
The only thing I can think of, at this point, is adding a way to pass in the ca cert to Gibbon's initializer. I'd need help testing that though, as I haven't been able to reproduce this problem.

**Comment by argent-smith** [comment]
May the problem be because of a weird mailchimp’s cert without a regular CA
cert in standard Ubuntu’s ca-certs file?

2016-03-30 21:49 GMT+03:00 Amro Mousa <notifications@github.com>:

> The only thing I can think of, at this point, is adding a way to pass in
> the ca cert to Gibbon's initializer. I'd need help testing that though, as
> I haven't been able to reproduce this problem.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/amro/gibbon/issues/173#issuecomment-203575905>
>



-- 
Yours truly, Pavel.

**Comment by amro** [comment]
@argent-smith It's possible. I know MC's API goes through a CDN. It's possible it's not properly configured. I've asked about this in the past, in fact. :(

**Comment by tboyko** [comment]
I contacted mailchimp about this a couple of months ago. Here is the explanation I received:

> Unfortunately, we have been seeing some recent SSL connection errors with Debian/Linux.
> 
> To provide a little more information, we are still using a root certificate that is signed by a 1024 bit RSA key due to compatibility with older clients, browsers, and versions of curl and OpenSSL. Due to the most recent update to Debian distros, that root signing key was removed as it's considered unsecure now by Mozilla. The root CA cert we are still using is called "GET_CyberTrust_Global_Root.crt".
> 
> Our Ops team is still determining the best solution that will have a minimal impact to our users, as they are aware of the recent updates removing that root cert. In the meantime, adding that cert back to your library should resolve the issue and get connectivity back. Check out this great resource for getting that added back: https://www.drupal.org/node/2477693#comment-10785922; you can find it under Solution.

After pushing for more information, I received:

> I'm a Technical Advisor here at MailChimp, I wanted to reach out to you about your ticket with us regarding SSL certificates.
> 
> Recently, certain distributions have been excluding the SSL certificate mentioned in our earlier email.  While many organizations are looking to move to more secure certificates in the future, currently our upstream service provider has not yet been able to provide us with a stronger alternative.
> 
> While we are working to add a newer root certificate with a stronger signing algorithm, presently we would not recommend disabling SSL verify, as this could certainly be a security issue.  Instead, re-adding the GTE certificate mentioned would be a much more secure method, as this would continue to use SSL, however it would use the SHA-1 signed certificate, which is still valid through 2017.
> 
> When these updates to the stronger certificates take place, they'll be accessible without needing to change your server's settings.  

Hope this helps.

**Comment by argent-smith** [comment]
Ok, I’ll try to check this solution and. If works we may create a README
entry on the subject. Thanks a lot for all your concerns!

2016-03-30 23:26 GMT+03:00 Taylor Boyko <notifications@github.com>:

> I contacted mailchimp about this a couple of months ago. Here is the
> explanation I received:
>
> Unfortunately, we have been seeing some recent SSL connection errors with
> Debian/Linux.
>
> To provide a little more information, we are still using a root
> certificate that is signed by a 1024 bit RSA key due to compatibility with
> older clients, browsers, and versions of curl and OpenSSL. Due to the most
> recent update to Debian distros, that root signing key was removed as it's
> considered unsecure now by Mozilla. The root CA cert we are still using is
> called "GET_CyberTrust_Global_Root.crt".
>
> Our Ops team is still determining the best solution that will have a
> minimal impact to our users, as they are aware of the recent updates
> removing that root cert. In the meantime, adding that cert back to your
> library should resolve the issue and get connectivity back. Check out this
> great resource for getting that added back:
> https://www.drupal.org/node/2477693#comment-10785922; you can find it
> under Solution.
>
> After pushing for more information, I received:
>
> I'm a Technical Advisor here at MailChimp, I wanted to reach out to you
> about your ticket with us regarding SSL certificates.
>
> Recently, certain distributions have been excluding the SSL certificate
> mentioned in our earlier email. While many organizations are looking to
> move to more secure certificates in the future, currently our upstream
> service provider has not yet been able to provide us with a stronger
> alternative.
>
> While we are working to add a newer root certificate with a stronger
> signing algorithm, presently we would not recommend disabling SSL verify,
> as this could certainly be a security issue. Instead, re-adding the GTE
> certificate mentioned would be a much more secure method, as this would
> continue to use SSL, however it would use the SHA-1 signed certificate,
> which is still valid through 2017.
>
> When these updates to the stronger certificates take place, they'll be
> accessible without needing to change your server's settings.
>
> Hope this helps.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/amro/gibbon/issues/173#issuecomment-203617930>
>



-- 
Yours truly, Pavel.

**Comment by dejongnj** [comment]
Has anyone figured this out? I'm new to development and am going through the Rails Tutorials on https://tutorials.railsapps.org/ and got an error message:

Gibbon::MailChimpError at /visitors
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil

I'd love to know how to fix this!

**Comment by amro** [comment]
@dejongnj did you read @tboyko's post, which MailChimp recommended as the solution for now?

**Comment by dejongnj** [comment]
@amro I'm new to all this so yes, I'm going through the solutions but I am struggling to make sense of much of it and how it applies to my situation. I am running in development mode on the local WEBrick server for rails when I got this error. I'll keep trying stuff though, :)

**Comment by amro** [comment]
@dejongnj Sorry this is difficult. Try the solution that suggests adding the GET root certificate back on your system. It's no longer considered secure so it has been removed from some operating systems. MailChimp's CDNs, as I understand it, still require this. They're working on fixing that but for now it's necessary. Otherwise, I think you should contact MailChimp support directly to see if they can help - they know more about their setup than anyone here will. And please do share if you find a solution.

**Comment by argent-smith** [comment]
I’ve solved the issue with the custom certificate which is the official
Mailchimp solution. Sorry for not writing long: deadlines are everywhere ;)

2016-04-22 0:14 GMT+03:00 Amro Mousa <notifications@github.com>:

> @dejongnj <https://github.com/dejongnj> Sorry this is difficult. Try the
> solution that suggests adding the GET root certificate back on your system.
> It's no longer considered secure so it has been removed from some operating
> systems. MailChimp's CDNs, as I understand it, still require this. They're
> working on fixing that but for now it's necessary. Otherwise, I think you
> should contact MailChimp support directly to see if they can help - they
> know more about their setup than anyone here will. And please do share if
> you find a solution.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/amro/gibbon/issues/173#issuecomment-213116862>
>



-- 
Yours truly, Pavel.
