### ISSUE TITLE
Add dynamic field in Contacts on Mailchimp

### ISSUE THREAD

**Issue by SachinGoyal** [amro/gibbon#175]
Is there any way in mailchimp to create list with custom field or add custom field after creating list with help of gibbon Gem or with mailchimp API v2

**Comment by amro** [comment]
It used to be that the field needed to be created on the list. So you would need to make an additional request before creating a member if you wanted to do that. I assume that's still the case but I am not certain. Please check MailChimp's docs and contact their support folks for this one.

--
Amro

**Comment by SachinGoyal** [comment]
I am looking for method for adding field to list after creating 
I got this from mailchimp

{
    "apikey": "example apikey",
    "id": "example id",
    "tag": "example tag",
    "name": "example name",
    "options": {
        "field_type": "example field_type",
        "req": true,
        "public": true,
        "show": true,
        "order": 42,
        "default_value": "example default_value",
        "helptext": "example helptext",
        "choices": [
            "..."
        ],
        "dateformat": "example dateformat",
        "phoneformat": "example phoneformat",
        "defaultcountry": "example defaultcountry"
    }
}

But don't know how to integrate in my application
