### ISSUE TITLE
Update member email

### ISSUE THREAD

**Issue by casper91** [amro/gibbon#178]
Is it not possible to update the members emails anymore?
```Ruby
lists(list_id).members(email_md5).upsert(body: { email_address: @user.email, status: "subscribed" })
```
It works fine for status.

**Comment by amro** [comment]
I don't have enough information to help. Are you receiving an error or is nothing happening? Something to check: upsert support was added in v2.1. Are you running 2.1+?

**Comment by casper91** [comment]
No errors. It returns the changed member, and I can see it change the status field fine (e.g. 'unsubscribed' -> 'subscribed' or vice versa). 
Tried with 2.2.1 and 2.1.3.

**Comment by amro** [comment]
Thanks for the detail. Unfortunately, I'm at a loss on this one. I tried both using Gibbon and using curl w/ MailChimp's [example](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash) and reproduced the same behavior you did.

I suggest contacting MailChimp's API support to see if there is, perhaps, some detail missing from the documentation. I'll leave this open - please share what you find in case there's something I should change in Gibbon (even if it just means updating the documentation).

**Comment by casper91** [comment]
Ok, I will write to them and comeback with an answer.

**Comment by amro** [comment]
Thanks. I'm looking into your other question now.

**Comment by casper91** [comment]
Response from MC:
> Yes, that's correct. It is not currently possible to change the email of a subscriber without creating a new subscriber.
He said he would pass it on to the documentation guys, to write, that this field is read-only (but lets see).
So I guess you would need to use create, since upsert/update does the same and won't create a new one for you (even though documentation says it would) at least what I can see.

**Comment by amro** [comment]
Thanks for getting back to me. I must say, that was not apparent to me. Glad they're adding documentation. Their API docs are generally very good.
