### ISSUE TITLE
groupings syntax

### ISSUE THREAD

**Issue by bbnnt** [amro/gibbon#180]
Hi, I'm getting back here to get some explanations about the groupings methods, the way to use it
So far I have this :
```
gb.lists(list).members.create(
          body: {
            email_address: self.email,
            status: "subscribed",
            merge_fields: {
              "FNAME" => "#{self.firstname}",
              "LNAME" => "#{self.lastname}"
              "GROUPINGS" => [
                { name: "Interests", :groups => ["design","journalism","tech"]}
              ]
            }
          }
        )
```

Thing as one's could understand, does not work :

```
Gibbon::MailChimpError: the server responded with status 400 @title="Invalid Resource", @detail="The resource submitted could not be validated. For field-specific details, see the 'errors' array."
```

A group is created on the specified list on mailchimp, this group contains the subgroups (design, journalism, tech, etc…)
But I feel like I'm missing something somewhere, and it seems as obvious as it breaks
Thanks for any help

**Comment by amro** [comment]
Hi @bbnnt, Interest groups are managed independent of merge fields. Please see MailChimp's [API doc](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/). Specifically, notice you need to pass interest groups as a separate `interests` parameter. And notice the description of how you should pass that parameter. There's an example in Gibbon's [README](https://github.com/amro/gibbon) file that should help as well.

If you have super deep questions about the API itself, please contact MailChimp's API support. They actually know the ins and outs of specific calls much better than I do. But I'm always happy to help with anything specific to Gibbon.

**Comment by bbnnt** [comment]
A lot, but I understand better why I got confused (or you'll tell me)

I'm using a group with the option "As checkboxes (people can select more than one)", so you yeah you do subscribe to a group, but more specifically I'm looking into assigning one or more of the option specified as choices in the group (hope I'm clear… here's a capture https://s3.amazonaws.com/f.cl.ly/items/273r252x0X3C152y3k1w/Screen%20Shot%202016-02-18%20at%2015.55.35.png?v=ab5fd6d8). For this, I don't see anything anywhere :/

From the README, `g.lists(list_id).interest_categories.retrieve` does return the id of the group (so far what I've understood), but i don't where to get the nested choices, and how to assign them

**Comment by amro** [comment]
You fetch the options themselves doing something like this:

    g.lists(list_id).interest_categories(interest_category_id).interests.retrieve

Then you'll get the ids back per checkbox, and you can update interests like that. The API docs are super helpful here. Look at the paths MailChimp has in their docs and map it onto Gibbon's call syntax. [For example](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/interest-categories/interests/):

    /lists/{list_id}/interest-categories/{interest_category_id}/interests

maps to

    g.lists(list_id).interest_categories(interest_category_id).interests.retrieve
