### ISSUE TITLE
Adding merge fields to a list

### ISSUE THREAD

**Issue by shreyaq3** [amro/gibbon#181]
Hi
I'm trying to add merge fields to a list, corresponding to the [following api](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/merge-fields/)
Following is my code
```
begin
  gb.lists(list_id).merge_fields.create({
    body: { name: 'var1', type: 'text' }
  })
rescue Gibbon::MailChimpError => e
 puts "We have a problem: #{e.message} - #{e.raw_body}"
end
```

I'm not get anything in the error message
`We have a problem:  - `

What am I doing wrong?
Is merge_fields method not supported?

**Comment by amro** [comment]
I'm not sure why you're not seeing a better error. This worked fine for me:

    g.lists(mylistid).merge_fields.create(body: {name: "myvar", type: "text"})

You shouldn't need the outer hash at all. I would check to make sure your list_id is not null.

**Comment by shreyaq3** [comment]
Not sure why this wasn't working earlier. 
Works like a dream now.
