### ISSUE TITLE
Testing the response of Mailchimp

### ISSUE THREAD

**Issue by stefanvermaas** [amro/gibbon#182]
Hi @amro,

I've got the Gibbon gem integrated in a service object (PORO), which I want to test. So I'm sure that errors are handled correctly. A bit more context: I use Gibbon to handle subscriptions for my mailchimp lists.

So this is what goes wrong; When I'm testing it, (by calling the service), I'm getting the error `Gibbon::GibbonError: - You must set an api_key prior to making a call`. Which is strange, because when I inspect the `Gibbon::Request` object in the service and in the spec, the API key is set.

Any thoughts on this?

Cheers!

PS: The testing code:

```ruby
   # spec.rb
    context 'with non-exsting e-mail address' do
      it 'successfully subscribes the new user to the list' do
        expect(service.call).to be_truthy
      end
    end

  # service.rb
  # Subscribes a user to the weekly mailinglist
  # @param user [User] the user
  def call
    weekly_list.members.create(body: request_body)
  end
```

**Comment by amro** [comment]
Hi @stefanvermaas. I'm not entirely clear on what's happening. Let's set the tests aside for a moment: If you make a call through your service object to subscribe a user, does it work or do you get this same error?

It does not make sense for you to get that error if you've set an API key either statically or when initializing the Gibbon instance. What version of Gibbon are you using?

Back to testing: I'm not sure what's happening here. How is weekly_list defined? `g.lists(list_id)`? That should be fine. To (perhaps) add some clarity, Gibbon doesn't map MailChimp entities onto objects. It just constructs a URL using the builder pattern based on the call chain and makes a request when some predefined verb terminator is called.

**Comment by stefanvermaas** [comment]
Hi @amro,

Sorry for the delayed response. I've found the problem: I retrieved the API key for Mailchimp from my sercrets.yml, but I hadn't set the API key for my test environment... My mistake, thanks for looking into it anyway!

Cheers

**Comment by amro** [comment]
Glad you figured it out

Thanks,
Amro
