### ISSUE TITLE
"certificate verify failed" in production

### ISSUE THREAD

**Issue by astjohn** [amro/gibbon#185]
Just recently, I've started to encounter `certificate verify failed` errors on our production servers when Gibbon interacts with mailchimp. I'm not sure why things have changed recently and any help is greatly appreciated.

```
gibbon (2.1.0)
rails (4.2.4)
jruby (9.0.3.0)
```

Thanks.

**Comment by amro** [comment]
I haven't changed anything relating to SSL validation in gibbon, other than merging a way for one to disable it (not recommended for production, obviously).

This is some weird configuration issue. Faraday has a [page](https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates) that describes how to configure around it.

There's additional discussion [here](https://github.com/amro/gibbon/issues/173). Most folks had luck exporting an environment variable.

**Comment by daveespo** [comment]
@astjohn, are you seeing this error sporadically? 

I thought y'all were crazy until I was doing some heavy API callouts and spontaneously (in the middle of a run where dozens of API calls were made prior) I'd pop a "SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server certificate B: certificate verify failed"

From that point forward, the Ruby process was horked and I'd need to relaunch the ruby worker ... almost as if the SSL stack was corrupted in process

**Comment by amro** [comment]
See this [discussion](https://github.com/amro/gibbon/issues/173), which explains that the issue is on MailChimp's end and provides a workaround.
