### ISSUE TITLE
Batch Operations

### ISSUE THREAD

**Issue by jgoodall628** [amro/gibbon#191]
Hello, I am using gibbon to subscribe the users on my website to mailchimp. Is there a way to batch subscribe my current users? I am reaching the request limit when I try to do it manually and was wondering if there was a way to do it in bulk using Gibbon.

**Comment by amro** [comment]
Yes, you should be able to after reading up on MailChimp's batch operations API. You'll have to construct the payload as MailChimp's API requires. There's info [here](http://developer.mailchimp.com/documentation/mailchimp/reference/batches/) and a bit more [here](http://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-batch-operations/). Hope that helps!

**Comment by noiseunion** [comment]
@jgoodall628 did you get things figured out?

@amro - it would be nice to have an example of using Gibbon for batch operations in the Readme?  It took me a while to figure it all out.

**Comment by amro** [comment]
Would you like to contribute an example?

**Comment by noiseunion** [comment]
yeah I could probably do that.  I'll fork and see if I can write something up tonight.

**Comment by amro** [comment]
Thank you, @noiseunion. It doesn't need to be anything super fancy. I prefer for folks to look at MC's API doc as their primary reference since Gibbon is really a very simple 1:1 wrapper around it. That's the goal, at least. :)

**Comment by noiseunion** [comment]
@amro I made the pull request.  LMK you want more detail, or changes made.

**Comment by amro** [comment]
thanks @noiseunion
