### ISSUE TITLE
404 when trying to unsubscribe a member

### ISSUE THREAD

**Issue by natanio** [amro/gibbon#194]
When I try the below, I get a 404 error. Is anyone else experiencing this?

`gibbon.lists(list_id).members(lower_case_md5_hashed_email_address).update(body: { status: "unsubscribed" })`

**Comment by amro** [comment]
This is working just fine for me

    gibbon.lists(list_id).members(lower_md5_hashed_email).update(body: {status: "unsubscribed"})

To my eyes it is identical to what you've done. A 404 generally means the resource wasn't found so check your list and member ids to make sure they're correct.

**Comment by natanio** [comment]
Ok, all good now. Wasn't setting the user id correctly. Thanks!
