### ISSUE TITLE
Gibbon::MailChimpError: the server responded with status 500 

### ISSUE THREAD

**Issue by zainaweb** [amro/gibbon#195]
Am getting the following error which seems to be on the Mailchimp but thought id open a ticket: 

Gibbon::MailChimpError: the server responded with status 500 @title="Internal Server Error", @detail="A deep, internal error has occurred during the processing of your request. Please contact support.", @body={"type"=>"about:blank", "title"=>"Internal Server Error", "status"=>500, "detail"=>"A deep, internal error has occurred during the processing of your request. Please contact support.", "exception"=>"9b5827785cda110dce282058b7596e6a", "instance"=>"050aaf68-041c-4bd4-a6c0-56b09f5d7abd"}, @raw_body="{\"type\":\"about:blank\",\"title\":\"Internal Server Error\",\"status\":500,\"detail\":\"A deep, internal error has occurred during the processing of your request. Please contact support.\",\"exception\":\"9b5827785cda110dce282058b7596e6a\",\"instance\":\"050aaf68-041c-4bd4-a6c0-56b09f5d7abd\"}", @status_code=500

**Comment by amro** [comment]
Yep, this is an error on the server and not in Gibbon.

Thanks!

**Comment by ronakjain90** [comment]
I'm having the same issue. Any idea, whats causing this?

**Comment by amro** [comment]
No, please ask MailChimp support about your specific error. It could be anything.
