### ISSUE TITLE
Webhooks on list do not fire when user is added to list using gibbon gem

### ISSUE THREAD

**Issue by jessesanford** [amro/gibbon#197]
I have a webhook setup on my list set to fire when a user is added to the list. I am able to confirm that this works by manually adding a user to the list in the mailchimp admin panel. The webhook does not fire when the user is added to the list using the gibbon gem. I have also confirmed that the webhook is set to fire for users added via the mailchimp API.

**Comment by amro** [comment]
All the gem does is call construct a request and hit the API. It passes exactly the same params you tell it to without modification. So something about the request you're making with Gibbon and the request you're making manually is different. You need to track that down.

**Comment by jessesanford** [comment]
Have you had any experience with this working on your end? If not I guess I will need to reconstruct the api call to confirm that it is their api endpoint that is not working as expected.

**Comment by amro** [comment]
I'm not currently using webhooks.

I need more information to help but I suspect this is a configuration issue and not a problem with MC's API or Gibbon. MC's API does a lot and behavior sometimes it isn't clear.

I would start by looking at the webhook you've configured to make sure it triggers based on the events you want. For instance, subscription is different from a profile being updated or an unsubscribe. Also, I'm not sure how webhooks behave if you attempt to subscribe somehow who's already been subscribed to the list but has unsubscribed. One more thing -- I'm not sure whether enabling or disabling double opt-in impacts webhooks. I think something like that is likely to be the problem.

If you can give me more detail, I might be able to help track it down but for API behavior questions you should contact MailChimp's API support team. They know their API behavior inside and out. Gibbon is simply a very light request wrapper. Nothing more.

There's some detail [here](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/webhooks/) (click "show properties" under events) if you haven't already seen it.

**Comment by jessesanford** [comment]
Specifically I am using the slack integration. Slack automatically creates the webhook for me. The issue is that when I add a user to the list manually via the mailchimp admin "add subscriber" form the webhook fires. If I use the gibbon gem to add a user to the list it does not fire. If I use the mailchimp api playground to perform the "POST lists/LIST_ID/members" with the following contents:
`{
	"email_address": "jesse+mailchimptest3@savethatname.com",
	"status": "subscribed",
	"status_if_new": "subscribed"
}`

the email address is successfully added to the list but the webhook does not fire.

The webhook itself is set to:

"What type of updates should we send?"
CHECKED "subscribes"

"Only send updates when a change is made …"

CHECKED "by a subscriber"
CHECKED "by an account admin"
CHECKED "via the API"

so I would assume that since the webhook fires when a user is added via the mailchimp admin and since the "via the API" box is checked that using the api to add a user would in fact call the webhook right?

**Comment by jessesanford** [comment]
The interesting thing is that if I use the edit endpoint on the member resource in the api playground to save an edit to a user the webhook does fire. This of course is only after I set the webhook to fire on "profile updates" or "email changed" in the webhook's detail page in the mailchimp admin.

**Comment by amro** [comment]
Since the webhook is not firing for a subscription via Gibbon and MC's playground page then this is likely some behavioral nuance. Please ask MC's API support team what that might be.

Try setting the status to "pending" instead. Perhaps the idea is if you're subscribing the user via the API, you already know about the change so there's no point in triggering the webhook.

Yep, I would expect the webhook to be triggered when "via the API" is checked.
