### ISSUE TITLE
HTTP Logging

### ISSUE THREAD

**Issue by flivni** [amro/gibbon#198]
Not sure if this has been discussed before, but I'd love to have HTTP logging in Gibbon. 

Note: I'm not familiar with the Gibbon code or with Faraday so perhaps I'm overlooking something and this functionality is already supported!

There are a few different approaches that I can think of:

(1) Add a faraday_builder parameter to the Request constructor -- similarly to how faraday_adapter is currently supported. 
(2) Have a debug or logging flag passed into the Request constructor.
(3) Have a logging_middleware parameter in the Request constructor that will be passed to Faraday as a builder option.

Anyone else want logging?
I'm happy to implement. Opinions on approach?

**Comment by amro** [comment]
@flivni Thanks for offering to contribute to Gibbon! To make sure I understand, you'd like to be able to set the logger, as in the first example in Faraday's README, for easier debugging?

e.g.
```
conn = Faraday.new(:url => 'http://sushi.com') do |faraday|
    faraday.request  :url_encoded
    faraday.response :logger
end
```
Is that right?

If so, I prefer approach 2, which is to pass a flag to the constructor called `http_logging` or similar. I'd appreciate tests for the two cases (true/false) and the parameter should have a default value of false. Let me know if you'd like to take this on.

**Comment by flivni** [comment]
@amro - Yes, exactly right.

I'd love to take this on.

Re option (2). I think this is the simplest approach and gives most people what they want. 
Note: I would pass the bodies parameter to the logger so logging would include the bodies not just headers, i.e.

```
conn = Faraday.new(...) do |faraday|
    ...
    faraday.response :logger, ::Logger.new(STDOUT), bodies: true
    ...
end
```

The negative of option (2) is that you can't use a custom logger / custom parameters. 

I took a look at a few different gems that use Faraday and they all seem to approach this issue differently. I think option (1) is the most flexible, but it makes it harder to just add logging. :/

Ultimately, I think it would be nice to be able to add/replace arbitrary middleware without having to replace the whole stack, but I don't see a good pattern for doing this.

If you still like option (2), I'll implement this weekend.

**Comment by amro** [comment]
Sounds good. I still prefer option 2. Thanks for suggesting it and offering to contribute the feature.

**Comment by flivni** [comment]
Sounds good. I'll implement this weekend.

**Comment by flivni** [comment]
I added a pull request: https://github.com/amro/gibbon/pull/199

The CI build is failing with 4 tests failing. I don't think I broke it. Here is one of the errors:
`expected Gibbon::MailChimpError, got #<WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. `

Also, when I run the tests locally, I get one failing test: "Gibbon supports upsert request"
The error is: 
```
     Failure/Error: .upsert(body: request_body)
     Gibbon::MailChimpError:
       undefined method `on_request' for #<Proc:0x007f5494a752e8> @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil

```

**Comment by amro** [comment]
Weird. I'll take a look in the morning.

**Comment by amro** [comment]
And thanks for the PR

**Comment by amro** [comment]
I wonder if "debug" is reserved by some library doing silly things when running tests

**Comment by flivni** [comment]
Interesting idea. I could rename. Maybe you could take a quick look first, though. I don't now how to trigger a CI build without checking in code.

Note: The local test failure occurs without my commit. So, unrelated.

**Comment by amro** [comment]
Oddly enough the tests run fine locally. Trying your patch locally now.

**Comment by amro** [comment]
Not your fault. The issue is webmock moved to 2.x and I had not locked it to 1.x in the Gemfile for some reason. I'll have to update the tests later.

**Comment by amro** [comment]
Thanks a bunch for contributing this!
