### ISSUE TITLE
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):

### ISSUE THREAD

**Issue by vonromson** [amro/gibbon#200]
I'm having this error.
this occurs when,
1. entered email address on the subscribe field.
2. hitting the button subscribe, throws an error to the console which is really frustrating to solve beacause there are no clear information on how to fix it.

ERROR on Terminal:
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):

Data Error: {"readyState":4,"responseText":"OpenSSL::SSL::SSLError in ApplicationController#subscribe\n\nSSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed.

im using "xxxxxxxxxxxxxxxxxxxxxxxxx0-**us13**" Api key.

i dont want to disable my ssl validation.

please help me out. thank you guys!

**Comment by amro** [comment]
Hi @vonromson. The short of it is this is an issue with MailChimp's CDN. There's a "solution" in issue #173 that involves adding a cert to your machine. I don't know of another way to work around this without disabling SSL validation. And that's clearly a bad thing to do as well.
