### ISSUE TITLE
404 issue with gibbon v2.2.4 and MailChimp API v3

### ISSUE THREAD

**Issue by antwonlee** [amro/gibbon#203]
I am getting 404 errors... it happens at `.create`

MailChimp API call response says:

`The requested resource could not be found.`

```ruby
MAILCHIMP = Gibbon::Request.new(api_key: ENV["MAILCHIMP_API_KEY"], debug: true)
Gibbon::Request.timeout = 15
```

```ruby
  def create
    subscribe_user_to_mailing_list
  end

  private

  def subscribe_user_to_mailing_list
    MAILCHIMP.lists.(ENV["MAILCHIMP_LIST_ID"])
      .members
      .create(
        body: {
          email_address: params[:subscribes][:email_address],
          status: "subscribed",
          interests: {
            "some_id1": params[:subscribes][:something1],
            "some_id2": params[:subscribes][:something2],
            "some_id3": params[:subscribes][:something3],
            "some_id4": params[:subscribes][:something4],
            "some_id5": params[:subscribes][:something5]
          },
          merge_fields: {
            FNAME: params[:subscribes][:first_name],
            LNAME: params[:subscribes][:last_name]
          }
        }
      )
  end
```

The interests are interest category ids, which I got from:
http://developer.mailchimp.com/documentation/mailchimp/reference/lists/interest-categories/

I am following syntax from README, but not quite sure what I am doing wrong.

---

Here is the error message in the log:

> the server responded with status 404 @title="Resource Not Found", @detail="The requested resource could not be found.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Resource Not Found", "status"=>404, "detail"=>"The requested resource could not be found.", "instance"=>""}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Resource Not Found\",\"status\":404,\"detail\":\"The requested resource could not be found.\",\"instance\":\"\"}", @status_code=404

**Comment by antwonlee** [comment]
Fixed the problem.

I had extra dot:
`MAILCHIMP.lists.(ENV["MAILCHIMP_LIST_ID"])`

fixed it with:
`MAILCHIMP.lists(ENV["MAILCHIMP_LIST_ID"])`

I can't believe that was what was causing the problem.  Arg :weary:

**Comment by amro** [comment]
Glad you figured it out!
