### ISSUE TITLE
open_timeout

### ISSUE THREAD

**Issue by atomical** [amro/gibbon#206]
Is there a way to set open_timeout or is that set by default when timeout is set?

**Comment by amro** [comment]
There is not a way to set open_timeout. Care to submit a pull request? 

If not, I can get to it soon.

**Comment by michielboekhoff** [comment]
This has been fixed by #224.

**Comment by amro** [comment]
I need to document this and change a couple of small things. I'm on vacation at the moment but I'll get to this very soon. Thanks to @michielboekhoff for his contribution.
