### ISSUE TITLE
Fake Gibbon for tests

### ISSUE THREAD

**Issue by pablo-co** [amro/gibbon#207]
I have used gibbon in several projects which are test driven. Yet for every single one of them we had to write integration and unit tests where at some point we had to interact with Mailchimp. 

Hitting a web service during automated tests is far from ideal, so we end up using a fake which simulates the parts of Gibbon we are testing. What is your stance about adding something like this to gibbon itself?

I would have no problem in doing a PR with a lightweight fake that can be used to test most of the general usage cases for gibbon if it looks like a right fit.

**Comment by amro** [comment]
I'm absolutely open to testing contributions. Thank you for offering to contribute.

**Comment by tmilker** [comment]
@pablo-co @amro Did this ever go anywhere?  I'd like to be able to use gibbon in tests without actually sending anything.
