### ISSUE TITLE
Campaign to a 'group' that matches a 'merge field'

### ISSUE THREAD

**Issue by jwgrenning** [amro/gibbon#208]
Hello

I'd like to send a campaign to a subset of the mailing list.  On the mailchimp website it asks "To which list shall we send?".  The options allow me to select a new group or segment.  I'd like to send to a group that has a custom merge field that matches a specific value.

Does the API support this?

thanks

**Comment by jwgrenning** [comment]
If not, can I create (and destroy) a segment with gibbon?

**Comment by amro** [comment]
Hi @jwgrenning,

Gibbon supports (afaik) everything MailChimp's API does. It's a 1-to-1 wrapper around API version 3. 

You can send campaigns with segments, but I've only personally done so to entire lists with Gibbon. It shouldn't be difficult though. See MailChimp's docs on [creating a campaign](http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/) with their API. The Recipients field, in particular, lets you specify a segment. There's an example of passing a segment_id in Gibbon's [readme](https://github.com/amro/gibbon) (search for "Create a new campaign" on the page).

I haven't personally used Gibbon to create segments, but it should work just fine. Take a look at the [list segment API docs](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/#create-post_lists_list_id_segments) for more info.

If you have questions about how the API works, please contact MailChimp's support team. They know it much better than I do. Once you understand how a given API endpoint works, it's usually easy to figure out how to format your request with Gibbon. There are a bunch of examples in the [readme](https://github.com/amro/gibbon).

If you have questions about how Gibbon works, I'm more than happy to answer them for you.

**Comment by jwgrenning** [comment]
Thanks Amro for the help.  I am not much of a web developer, I do it for 
fun and my business.  I'll see if I can figure this out and may ask for 
some other help.

thanks, James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by amro** [comment]
Sure thing. Feel free and good luck!

**Comment by jwgrenning** [comment]
I found this example.  
http://stackoverflow.com/questions/32849116/mailchimp-api-v3-cannot-create-segment


But after looking at a few other things, it seems maybe i don't want to 
create a new segment and save it, I want send to a group of subscribers 
that all share the same value of a merge field. It seems I may be able 
to create a segment on the fly for users that match a specific value of 
a merge field (my merge field is called COURSECODE, and I match for a 
specific course)

I'll let you know what I figure out, If you have any suggestions I'd 
love to hear them.

thanks, James
--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by amro** [comment]
I was out of town. Did you figure it out? In the example you found, the part passed as the options would likely passed as "segment_ops" as part of "recipients."

So it might look like this (you'll have to try this and debug as I am typing this directly into github and not into a Ruby console where I can check syntax):

```ruby
segment_options = {
    match: "any",
    conditions: [
      {
        condition_type: "TextMerge",
        field: "COURSECODE",
        op: "is",
        value: "CS Theory 1100"
      }
    ]
}

recipients = {
  list_id: list_id,
  segment_opts: {
    saved_segment_id: segment_id
  }
}

settings = {
  subject_line: "Subject Line",
  title: "Name of Campaign",
  from_name: "From Name",
  reply_to: "my@email.com"
}

body = {
  type: "regular",
  recipients: recipients,
  settings: settings
}

begin
  gibbon.campaigns.create(body: body)
rescue Gibbon::MailChimpError => e
  puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
end
```

I am far from certain that "condition_type" should be "TextMerge." Check MailChimp's docs or ask their API folks about that. Hope that helps.

**Comment by jwgrenning** [comment]
Thanks for the suggestions.  I have not gotten back to it yet.  I'll 
give you working example code once I get it working.

thanks, James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by jwgrenning** [comment]
Thanks!  I got it working.  Once I have it structured the way I want 
I'll send it to you.

James

**Comment by amro** [comment]
Great!
