### ISSUE TITLE
Gibbon::Request.throws_exceptions = false in v2

### ISSUE THREAD

**Issue by brendon** [amro/gibbon#217]
Hi there, just upgrading to version 2 and wondered if there was an equivalent setting for: `Gibbon::Request.throws_exceptions = false`?

Do I just have to rescue the calls if I don't want errors raised? :)

**Comment by amro** [comment]
Sorry @brendon. Not anymore. Yep, rescue is the way to go.

**Comment by brendon** [comment]
Thanks @amro :)
