### ISSUE TITLE
Gibbon::MailChimpError execution timeout

### ISSUE THREAD

**Issue by Michael1969** [amro/gibbon#219]
Hi,

` gibbon = Gibbon::Request.new(api_key: '12345', debug: false)`

`reports = gibbon.reports.retrieve(params: {count: 1})`

works perfect in development console, but not in production, get execution timeout all the time.
why?

thanks, Michael

**Comment by Michael1969** [comment]
sorry, my firewall blocked it.

**Comment by austinarchibald** [comment]
@Michael1969 I'm having the same issue. It works in development, not in production: 
`Gibbon::MailChimpError (Net::ReadTimeout @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil)`

I tried `sudo ufw disable` and `sudo service nginx restart` but I'm still getting the timeout. How did you resolve the issue? Thank you!
