### ISSUE TITLE
Gibbon::MailChimpError: No implicit conversion of Symbol into Integer 

### ISSUE THREAD

**Issue by SirRawlins** [amro/gibbon#220]
Morning Folks,

I'm seeing the error `Gibbon::MailChimpError: No implicit conversion of Symbol into Integer` on an intermittent, but fairly regularly basis when retrieving a collection of members for a list. Due to the intermittent nature I'm struggling to reproduce.

My call to request the members looks something like this: **Using Gibbon 2.2.1.**

```ruby
# Get a list of subscribers from the Mailchimp
# API who have unsubscribed recentyly so we can
# sync our subscriber list.
def recent_unsubscribers
  # Request the recent unscubscriptions from Mailchimp.
  # https://apidocs.mailchimp.com/api/how-to/sync-mailchimp-to-you.php
  backend.lists(self.email_mailchimp_list_id).members.retrieve(params: {
    :since_last_changed => email_mailchimp_last_synced_at, # Only pull since we last checked.
    :status => 'unsubscribed' # Only pull those unsubscribed.
  })['members']
end
```
And the initial top-level stack trace for the exception looks like this:

```
Gibbon::MailChimpError
no implicit conversion of Symbol into Integer @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil

gibbon/api_request.rb in handle_error at line 120

118    error_to_raise = MailChimpError.new(error.message, error_params)
119
120    raise error_to_raise
121 end
```

However when digging a little deeper into the raw trace I'm seeing mentions of the [Twitter](https://github.com/sferik/twitter) lib, which appears to be trying to handle/parse the error - perhaps a namespace conflict or something of that nature?

```
TypeError: no implicit conversion of Symbol into Integer
  from twitter/error.rb:75:in `[]'
  from twitter/error.rb:75:in `parse_error'
  from twitter/error.rb:39:in `from_response'
  from twitter/rest/response/raise_error.rb:15:in `on_complete'
  from faraday/response.rb:9:in `block in call'
  from faraday/response.rb:57:in `on_complete'
  from faraday/response.rb:8:in `call'
  from faraday/rack_builder.rb:139:in `build_response'
  from faraday/connection.rb:377:in `run_request'
  from faraday/connection.rb:140:in `get'
  from gibbon/api_request.rb:50:in `get'
  from gibbon/request.rb:56:in `retrieve'
  from app/models/publishers/email.rb:86:in `recent_unsubscribers'
  from app/models/publishers/email.rb:69:in `sync_unsubscribers'
  from delayed/performable_method.rb:26:in `perform'
```

Looks as though Faraday is using the wrong error handler to cope with the response?

**Comment by SirRawlins** [comment]
Looking through the CHANGELOG on the Twitter lib I can see they made some recent changes a while back to deal with namespace conflicts in Farday.

https://github.com/sferik/twitter/commit/a96931171e32c142f36318547f2cffa6ccd5c199

I'm currently running version behind on the Twitter lib which could well be what's causing this issue. I'm going to bump the version and see if it behaves any better, but as it's intermittent it'll take a while.

**Comment by SirRawlins** [comment]
One thing I also notice looking through the Gibbon codebase is that we ourselves do not namespace our faraday middleware.

https://github.com/amro/gibbon/blob/7632bad9816c481f61173f9aa9429d0af37d9798/lib/gibbon/api_request.rb#L135

So bumping the Twitter gem may solve my issue, but still likely leaves thing vulnerable to other clashes down the line.

If we're agreed this is the core issue I can send in a PR to namespace the Gibbon middleware?

**Comment by amro** [comment]
Robert,

Thanks for digging into this. Yes, please send a PR.

Thanks,
Amro

**Comment by SirRawlins** [comment]
@amro no problem. On reflection I actually don't think we have an issue in Gibbon as we're using the standard raise_error handler from Faraday, whereas Twitter is injecting their own custom raise_error middleware, which is where they were borking the namespacing.

So we don't need to make any changes. 👍

**Comment by grdmnt** [comment]
Hi. I'm using Gibbon 3.1.1 and this issue still comes up. Is this a conflict between two gems?

**Comment by amro** [comment]
Yes, that’s my understanding from the prior discussion. I’m not sure how Robert worked around it, candidly.

**Comment by SirRawlins** [comment]
@grdmnt @amro I can't honestly remember how I resolved this, but I'm fairly confident that updating my Twitter version meant the conflict wasn't happening anymore.

It might be Twitter, or another gem using Faraday which is catching errors rather than letting them bubble up to be handled by Gibbon.

Gerard, if you look down the full stacktrace, do you see anything deeper in the stack as I did in my comments above?

**Comment by grdmnt** [comment]
@SirRawlins I actually resolved this by updating the Twitter gem
