### ISSUE TITLE
Travis CI: remove rbx-2 testing?

### ISSUE THREAD

**Issue by michielboekhoff** [amro/gibbon#225]
Hello,

According to Travis, Rubinius has no available binaries. It seems Rubinius has no binary Rubies available for 2.*. We can remove it or build from source, this way the CI will not keep failing. This will also solve the CI issues with #224.

@amro, what do you think?

**Comment by amro** [comment]
Ah! I see. That sounds fine. Do you want to do that here? If not I can -- no problem
Thanks,
Amro

**Comment by michielboekhoff** [comment]
@amro Do you think gibbon should keep supporting it? I'll make a PR for it to be built from source.

**Comment by amro** [comment]
Ideally yes. Tyvm. I'm away from my personal machine for a few days so I very much appreciate your extra contribution here.

Thanks,
Amro

**Comment by michielboekhoff** [comment]
I'll make sure to try to make it work. I'll try to have a commit later today to fix it.

**Comment by michielboekhoff** [comment]
@amro,

I've had a look at the issue with Rubinius. There's no pre-built version for the OS Travis is running (Ubuntu Precise, 12.04 LTS), so understandably Travis fails. I think we might have an irreconcilable problem insofar that we'd have to ask them to build a pre-built. I've updated #224 to remove Rubinius, so as to pass tests. 

Regards,

Michiel.

**Comment by michielboekhoff** [comment]
Issue was resolved with the merging of #224.
