### ISSUE TITLE
Possible to specify version 2.x instead of 3.x of Mailchimp API?

### ISSUE THREAD

**Issue by Siggs2000** [amro/gibbon#226]
Is it possible to specify the version of the MC api that you want to target? Maybe in the gem initializer?

**Comment by amro** [comment]
API 2 is going away at the end of this year, as I understand it. You can use an old version of the gem to target that if you need it for now though.

Thanks,
Amro

**Comment by Siggs2000** [comment]
Thanks @amro - I was just reading about the depreciation as you were typing that. Thanks for your work on this gem too. Great stuff.
