### ISSUE TITLE
Cannot create static segment in a list

### ISSUE THREAD

**Issue by ubermensch** [amro/gibbon#228]
Hi there! Forgive me if I'm making a silly mistake, but I can't seem to work out how to craft the gibbon request payload so Mailchimp API doesn't barf. I keep getting:

```
Gibbon::MailChimpError: the server responded with status 400 @title="Invalid Resource", @detail="Must provide either an \"options\" field or a \"static_segment\" field"
```

This is what I've got:

```
# api is instance of `Gibbon::Request`
resp = api.lists(list.mailchimp_id).segments.create(body: {
  name: name,
  static_segment: [] # Create a new static segment with no subscribers
})
```

I've tried using `options` as described by the API docs [here](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/#create-post_lists_list_id_segments) but unsure of the payload it's expecting

Thanks in advance for any help you can provide!

**Comment by amro** [comment]
Hi @ubermensch. Sorry for the delayed response -- I've been traveling.

This exact thing worked for me:

    g.lists(list_id).segments.create(body: {name: "my segment", static_segment: []})

From what I see, this is identical to what you've tried. You shouldn't pass options when creating a static segment (per MailChimp's documentation).

The only thing I can guess is the error message returned by the API isn't quite right. Make sure the name is not nil or empty and make sure the list id is valid. Mine looked something like "310a7f2f55."

**Comment by ubermensch** [comment]
Thanks for checking the repro, @amro! I'll try again.

Happy holidays! 🎄

**Comment by amro** [comment]
Are you good to goo @ubermensch?

**Comment by ubermensch** [comment]
@amro Yep, I believe so. Thanks!
