### ISSUE TITLE
MailChimp error 404 - TypeError can't convert Gibbon::Request to Array

### ISSUE THREAD

**Issue by Jirka1111** [amro/gibbon#229]
Code:
    gb = Gibbon::Request.new(api_key: "my_api_id")
    puts "failed because"
    puts gb.error.raw_body
    gb.timeout = 15
    gb.throws_exceptions = true
    gb.lists("my_list_id").members.create(body: {email_address: "foo@bar.com", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})

Error from gibbon.error.raw_body:

failed because
[ActiveJob] [SubscribeUserToMailingListJob] [f9641310-050b-495b-93f6-0950df91f3fe] Performed SubscribeUserToMailingListJob from SuckerPunch(default) in 0.84ms
Sucker Punch job error for class: 'ActiveJob::QueueAdapters::SuckerPunchAdapter::JobWrapper' args: [{"job_class"=>"SubscribeUserToMailingListJob", "job_id"=>"f9641310-050b-495b-93f6-0950df91f3fe", "queue_name"=>"default", "arguments"=>[{"_aj_globalid"=>"gid://jozu/User/54"}], "locale"=>:en}]
TypeError can't convert Gibbon::Request to Array (Gibbon::Request#to_ary gives Gibbon::Request)

**Comment by amro** [comment]
Hi @Jirka1111, what's your question?

A few things off hand w/ the code you posted:

Throws_exceptions is set to true by default now. No need to set it again unless you really ant to.

You can't read the error like that. You need to make your call within a begin/rescue block and print the contents of the error there.

Check out the README for an example but you can enable a debug mode that'll print the response for you to make it easier to see what's wrong.

**Comment by Jirka1111** [comment]
I guess it did not help:

Houston, we have a problem: the server responded with status 404 @title="Resource Not Found", @detail="The resource 'ThrowsExceptions_Instance' could not be found.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Resource Not Found", "status"=>404, "detail"=>"The resource 'ThrowsExceptions_Instance' could not be found.", "instance"=>""}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Resource Not Found\",\"status\":404,\"detail\":\"The resource 'ThrowsExceptions_Instance' could not be found.\",\"instance\":\"\"}", @status_code=404 - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Resource Not Found","status":404,"detail":"The resource 'ThrowsExceptions_Instance' could not be found.","instance":""}

**Comment by Jirka1111** [comment]
Code:

```
begin
      gb = Gibbon::Request.new(api_key: "api_key")
      gb.timeout = 15
      gb.throws_exceptions = true
      gb.lists("list_key").members.create(body: {email_address: "fofdsfo@barfdsf.com", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})
    rescue Gibbon::MailChimpError => e
      puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
    end
```

My question is... Where is the problem? The code is from Readme, I use test data.

Thank you, amro.

**Comment by amro** [comment]
Remove the line to set throws_exceptions = true. I removed that option in Gibbon 2, which targets the new API. I forgot that above when I suggested you remove it.

**Comment by Jirka1111** [comment]
I cant believe it helped :) I wanted to remove it after your first answer but went to sleep. Your explanation is logical but it I did not realize it :-)

Thank you very much :)

Maybe this easy code should be in Readme:

```
   begin
      gb = Gibbon::Request.new(api_key: "your_api_key")
      gb.timeout = 15
      gb.lists("your_list_key").members.create(body: {email_address: "fofdsfo@barfdsf.com", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})
    rescue Gibbon::MailChimpError => e
      puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
    end
```

**Comment by amro** [comment]
Glad you got it working
