### ISSUE TITLE
Response from deleting a Segment from a List 

### ISSUE THREAD

**Issue by mangantj** [amro/gibbon#232]
I could be missing something so my apologize, but when ever I delete a segment from a list

`response = client.lists(list_id).segments(segment_id).delete`

the response is always coming back nil for me even though the api call was successful (Mailchimp no longer shows the segment).

Am I doing something wrong here?

**Comment by amro** [comment]
I'm not sure off hand. Can you please try enabling the debug flag to see what is returned?

Thanks,
Amro

**Comment by mangantj** [comment]
Sorry for the delay. Will be doing this shortly and get back.

**Comment by mangantj** [comment]
Alright Amro, here is the output I get with debug turned on

`User-Agent: "Faraday v0.9.1"
Authorization: "Basic YXBpa2V5Ojg1OWYyNjhiMDQ1YzgxOWUzYWE1ZjY5MTU2OTBiYjUzLXVzMTQ="
Content-Type: "application/json"

204
server: "openresty"
content-type: "application/json; charset=utf-8"
content-length: "0"
x-request-id: "45f4ab61-8a7e-4215-8473-9b018a3dee0d"
date: "Fri, 13 Jan 2017 18:30:38 GMT"
connection: "close"
set-cookie: "_AVESTA_ENVIRONMENT=prod; path=/"`

**Comment by amro** [comment]
So there’s no body at all. This seems like an intentional decision on MailChimp’s part (i.e. just check the status code). Does their API doc mention this, by chance?

**Comment by mangantj** [comment]
Ah good call. It says an example response 

```
HTTP/1.1 204 No Content
Server: nginx
Date: Thu, 12 May 2016 14:05:04 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 0
Connection: keep-alive
X-Request-Id: 1da966ab-8614-4a57-bbb3-1516815828ca
```
So that seems correct. Thank you for your help.

**Comment by amro** [comment]
No problem!
