### ISSUE TITLE
Not able to load rails console after adding this gem

### ISSUE THREAD

**Issue by jaswinder97** [amro/gibbon#233]
I am using discourse forum rails app (4.2.7.1)

when I did:
 `RAILS_ENV=development bundle exec rails c`

I am getting an error:
`/var/www/discourse/config/initializers/gibbon.rb:1:in `<top (required)>': uninitialized constant Gibbon::API (NameError)`

**Comment by amro** [comment]
What version of gibbon are you using? That syntax is for version 1.x. It changed in 2.x. Please see the readme on the tagged version of the source for the build you are using. The current readme on master is for an unreleased version (though it's mostly the same).

Thanks,
Amro

**Comment by amro** [comment]
I believe you updated from v1 of the gem w/o migrating to the new API. The README contains some examples of how to migrate from v1 to v2 or newer.

I'll close this now but let me know if you have questions.
