### ISSUE TITLE
Upsert method on list members has MailChimp return a 405 error

### ISSUE THREAD

**Issue by rovalcor** [amro/gibbon#235]
I'm requesting an upsert for members of a list.
```
gibbon = Gibbon::Request.new(api_key: api_key, timeout: 15, open_timeout: 15)
gibbon.lists(list_id).members.upsert(body: subscription_request_body)
```
However, MailChimp returns the following response:
```
title"=>"Method Not Allowed", "status"=>405, "detail"=>"The requested method and resource are not compatible. See the Allow header for this resource's available methods.", "instance"=>""
```

Seems like MailChimp has no problem with receiving a PUT method for list members (http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/). Is there a problem with my setup? FYI I'm running version 3.0.1.

**Comment by amro** [comment]
Hi @rovalcor. Have you seen the example in the README about this? Try something like this:

    gibbon.lists(list_id).members(lower_case_md5_hashed_email_address).upsert(body: {email_address: "foo@bar.com", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})

Note the lower_case_md5_hashed_email_address is passed

**Comment by rovalcor** [comment]
@amro Seems like that did the trick. Thank you very much!

**Comment by amro** [comment]
Glad to hear it! No problem at all

Thanks,
Amro
