### ISSUE TITLE
Upsert doesn't create new member, if status is 'subscribed'

### ISSUE THREAD

**Issue by wuarmin** [amro/gibbon#236]
Hello,
I like your gem. It is very easy to use :+1:  
I noticed a weird behaviour at upsert of new subscriber. It works as long the new member's status is 'unsubscribed'.

Following works. The if ressource devon.miles@foundation.com does not exist, it is created. 
```ruby
@connection.lists(list_id).members(Digest::MD5.hexdigest(email)).upsert(
{
    body: {
        email_address: "devon.miles@foundation.com",
                    :status: "unsubscribed",
          merge_fields: {
                 FNAME: "Devon",
                 LNAME: "Miles",
          }
       }
   }
)

```
Follwing fails with 'Invalid Resource'
```ruby
@connection.lists(list_id).members(Digest::MD5.hexdigest(email)).upsert(
{
    body: {
        email_address: "devon.miles@foundation.com",
                    :status: "subscribed",
          merge_fields: {
                 FNAME: "Devon",
                 LNAME: "Miles",
          }
       }
   }
)

```
Best regards

**Comment by amro** [comment]
I'm not sure why this would be. I've tested Gibbon just fine w/ upserts w/ the `status` being set to `subscribed`. I did notice the extra colon before `status` in the code above. Can you try removing that and giving it another go?

And to be clear, you aren't memoizing gibbon instances, right? There's a note in the README but it'll only work if you call a terminating verb like upsert(). I recommend against reusing Gibbon instances in general though.

**Comment by wuarmin** [comment]
Thank you for your fast response. 
Sorry, the extra colon is just a typo in my example pasted here.

We reused it but I removed it now. But the error still exists.

Here's a slim class: 
```ruby
require 'digest/md5'

class MailchimpRepository

def connection
    Gibbon::Request.new# debug: true
  end

  def upsert_subscriber(email:, list_id:)
    begin
         connection.lists(list_id).members(Digest::MD5.hexdigest(email)).upsert(
            {
               body: {
                  email_address: email,
                  status: "subscribed",
                  merge_fields: {
                     FNAME: "Devon",
                     LNAME: "Miles",
                 }
             }
         }
       )
    rescue Gibbon::MailChimpError => e
       puts "#{email} #{e.title}"
    end
  end
end

```

**Comment by amro** [comment]
Did you figure it out? That behavior could be intentional on MailChimp's part. i.e. you may not be able to programmatically subscribe someone who has unsubscribed for abuse reasons. It could be that you need to delete the email all together in that case.

**Comment by wuarmin** [comment]
Sorry, it was my fault. I turned on logging and saw following:
```
devon.miles@foundation.com has signed up to a lot of lists very recently; we're not allowing more signups for now
```
So Mailchimp is very strict and I did not know that. Thank you for your help.
