### ISSUE TITLE
Unsubscribe an Email Address giving 405 Method Not Allowed

### ISSUE THREAD

**Issue by ankitkapasi** [amro/gibbon#241]
This looks very much like the documentation but I keep getting a 405 error. From inside user.rb, I am calling.

     begin
        gibbon = Gibbon::Request.new
        gibbon.lists.unsubscribe(:id => ENV["SUBSCRIBERS_LIST_ID"],
                                 :email => {:email => self.email},
                                 :delete_member => false,
                                 :send_notify => false)
      rescue Exception => e
        AdminMailer.mailchimp_failure("Remove Subscriber", self, e).deliver_now
      end

The mail message I am getting back

Error in adding a user to the Mailchimp list: Remove Subscriber

User information:
Id: 363
Email: name@gmail.com
First Name: 
Last Name: 
Error message:

the server responded with status 405 @title="Method Not Allowed", @detail="The requested method and resource are not compatible. See the Allow header for this resource's available methods.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Method Not Allowed", "status"=>405, "detail"=>"The requested method and resource are not compatible. See the Allow header for this resource's available methods.", "instance"=>""}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Method Not Allowed\",\"status\":405,\"detail\":\"The requested method and resource are not compatible. See the Allow header for this resource's available methods.\",\"instance\":\"\"}", @status_code=405

**Comment by amro** [comment]
That is not the correct syntax. Are you using Gibbon 2 or 3 with Gibbon version 1 syntax? That's what it looks like to me. Please take another look at the README at http://github.com/amro/gibbon.

You'll see you should be making call similar to this:

```ruby
gibbon.lists(list_id).members(lower_case_md5_hashed_email_address).update(body: { status: "unsubscribed" })
```

**Comment by ankitkapasi** [comment]
@amro THANK! 

I was looking at the api_v2 branch documentation when I grabbed that syntax. I'll try out what you've suggested and update the issue :-)

**Comment by amro** [comment]
No problem at all

**Comment by ankitkapasi** [comment]
@amro to double check - i should use the syntax you provided for gibon 2.2.1?

**Comment by amro** [comment]
yes, v2 and v3 use basically the same syntax

**Comment by ankitkapasi** [comment]
@amro one more confirmation: is this a function that I need to implement or is it part of gibbon or rails?

`lower_case_md5_hashed_email_address`

**Comment by amro** [comment]
Please see the read me or MailChimp's API for more info about this, but you need to normalize the email address per MailChimp's requirements to create an ID to pass to the API.

The steps are

1. Trim whitespace
2. Lower case the email address
3. md5 hash the lower cased email address

**Comment by ankitkapasi** [comment]
@amro thanks once again.
