### ISSUE TITLE
Create new campaign

### ISSUE THREAD

**Issue by humberty** [amro/gibbon#242]
Hi.

I have doubt about create new campaign using the gibbon, 
I did step by step according to the documentation but when happens the error:

The server responded with status 400 @title="invalid resource", @detail="The resource submitted could not be validated.

my code:

def newCampaing()
		recipients = {
			list_id: @list,
			segment_opts: {
				saved_segment_id: nil
			}
		},
		settings = {
			subject_line: "Assunto",
			title: "Campanha Teste Integracao",
			from_name: "Nome",
			reply_to: "humberty.rogerio@codere.com"
		},

		body = {
			type: "regular",
			recipients: recipients,
			settings: settings,
			template: {
				id: @template_id,
			    sections: {
		        	"eventmessage": "Event Message Content"   
		        }
			}
			
		}
		begin
			campaign_hash =  @gibbon.campaigns.create(body: body)
			@campaign_id = campaign_hash['web_id']
			#puts @campaign_id['web_id']
			rescue Gibbon::MailChimpError => e
			puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
		end
		
	end

	def sendCampaing() #enviar campanha
		@gibbon.campaigns(@campaign_id).actions.send.create
	end
end

Help me , please ><

**Comment by amro** [comment]
Hi @humberty.

I need more information to help. It's not clear to me where the failure is from the information you've provided.

Is the campaign being created successfully? Is an id being printed by your code?

Which documentation are you referring to? Gibbon's? Have you looked at MailChimp's API documentation? That's the place to start if not.
