### ISSUE TITLE
Version 3.0.0??

### ISSUE THREAD

**Issue by fabn** [amro/gibbon#245]
I cannot find in gem history why export api was removed after introduction in 3.0.0 so I'm wondering why it was removed.

Also I was looking at that because I need to export a big list and `lists.members.retrieve` with pagination (I set page size to 1000 in this example) is veeeery slow, look at this:

```
Time: 00:06:09  ETA: 02:58:00  3.34% Processed: 4000 users from 119715
```

I want to try version 3.0.0 to rewrite my task to use the export api but I've just found out that version 3.0.0 was [yanked](https://rubygems.org/gems/gibbon/versions/3.0.0) in rubygems. Could you please restore it?

**Comment by amro** [comment]
My understanding is MC is not supporting the export API. They have an async batch API -- I'd suggest using that if possible.

Thanks,
Amro

**Comment by amro** [comment]
Also, there's a changelog [here](https://github.com/amro/gibbon/blob/master/CHANGELOG.md). I try to keep it up to date.

**Comment by daveespo** [comment]
FWIW, the async batch API is a flaky, unreliable, buggy, slow steamy mess. 

Mailchimp implicitly acknowledged this when they restored docs for the Export API (the first sentence kind of covers it)

https://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-the-export-api/

**Comment by fabn** [comment]
> My understanding is MC is not supporting the export API. They have an async batch API -- I'd suggest using that if possible.

AFAIK batch api cannot be used to retrieve list members, am I wrong?

> FWIW, the async batch API is a flaky, unreliable, buggy, slow steamy mess.
> 
> Mailchimp implicitly acknowledged this when they restored docs for the Export API (the first sentence kind of covers it)

I don't see any note about export api being buggy or slow. 

In any case their api is pretty slow as well, it takes about 90 seconds to retrieve 1000 subscribers with this curl

```
https://apikey:<MAILCHIMP_API_KEY>@us7.api.mailchimp.com/3.0/lists/<SOME_LIST_ID>/members?count=1000&offset=0
```

**Comment by amro** [comment]
I understand. I don't want to support something MC is not going to support. I'm going to ask for their plans directly. If they're supporting the Export API for a while then I'll add it back. If not then I will not.

Some months ago I asked about this and the response I got was it was not supported -- maybe that has changed. At the time I could no longer find to the Export API documentation (iirc) so I decided to pull support.

I do this in my spare time and don't always have time to respond to questions about API usage. It's important for me that MC is able to help people with usage questions and has documentation available.

I see there is documentation available for the Export API today.

**Comment by daveespo** [comment]
We spent almost 3 months struggling with support case after support case with Mailchimp on bugs in the big async operations in API 3.0 (batches that never finished, batches that had corrupted or zero length tarballs, batches that took 10s of hours to finish for only 10k records). Then, they published this:

https://devs.mailchimp.com/blog/api-v3-0-updates/

It basically told the story without explicitly saying it: API 3.0 is a mess when you are trying to retrieve large (100k+) subscriber data. And that they're **not** sunsetting the Export API 1.0.

I saw that you added the support back in in #230 but then backed it out immediately. What as the reasoning?

We appreciate the effort you put in -- and the fact that you try to help out folks that don't know how to draw the line between a light API wrapper and the API itself -- it's impressive. Thank you.

**Comment by amro** [comment]
Let's give MailChimp's API folks a chance to respond to my inquiry. They have been very helpful in the past. I understand you've had trouble with the batch API -- I didn't know this was a thing as I don't need to use MailChimp's API for large scale operations. It's good feedback for me to have as well as it's something I can take into account. 

As I mentioned above, my rationale is simply that I can't give time to support something MailChimp is not supporting. If I must field API-specific questions about the Export API (as opposed to their support folks being able to do so) then I have to commit more time or ignore those inquiries. That time would have to come from other, higher priority to be frank, obligations like work and family. I don't like the idea of being unresponsive either.

Anyway, let's give them a day or two to respond -- I need a little more information to make a decision. It won't take long to add it back if they tell me they intend to support the Export API for some time to come.

Thanks for your understanding.

**Comment by fabn** [comment]
@amro thanks for everything.

**Comment by amro** [comment]
I discussed this w/ someone in the know. I'll add export API support back to Gibbon. Please note that I will stop supporting it whenever MC does.

**Comment by amro** [comment]
Please see https://rubygems.org/gems/gibbon/versions/3.1.0

**Comment by daveespo** [comment]
Thanks!

**Comment by fabn** [comment]
Thanks
