### ISSUE TITLE
How to delete mailchimp list?

### ISSUE THREAD

**Issue by nfedyashev** [amro/gibbon#246]
Couldn't find it in usage examples and tests.

    mailchimp_client.lists(mailchimp_list_id).webhooks.delete(params: {id: '1694275d82'})

>delete https://us1.api.mailchimp.com/3.0/lists/9912b072bb/webhooks?id=1694275d82
Content-Type: "application/json"
>{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Method Not Allowed","status":405,"detail":"The requested method and resource are not compatible. See the Allow header for this resource's available methods.","instance":""}

https://developer.mailchimp.com/documentation/mailchimp/reference/lists/webhooks/
API docs states that URL should be in form of `DELETE /lists/{list_id}/webhooks/{webhook_id}`

Long story short
---

expected request:

> delete https://us1.api.mailchimp.com/3.0/lists/9912b072bb/webhooks/1694275d82

actual request:

>delete https://us1.api.mailchimp.com/3.0/lists/9912b072bb/webhooks?id=1694275d82

Any tips?
Thanks

**Comment by amro** [comment]
Yes. The issue is you've provided the id as a parameter instead of part of the path. Try this:
mailchimp_client.lists(mailchimp_list_id).webhooks("1694275d82").delete
I think that'll work though I'm not at my machine to try it at the moment.
Thanks,
Amro

**Comment by nfedyashev** [comment]
@amro it worked! Thank you very much!
