### ISSUE TITLE
Sending emails to people who are not in MailChimp

### ISSUE THREAD

**Issue by tylerbhughes** [amro/gibbon#248]
Hi, we've got several people subscribed to our newsletters in MailChimp. We've also got a separate website with a list of users who we have to routinely e-mail. It's possible that some people may be in both lists but not many. We'd like to update our site to send emails using MailChimp. Does your library allow for me to send an email if I provide it the email address (even if it's not subscribed to the campaign)? If so can you point me to the documentation that shows how to do this?

**Comment by amro** [comment]
I'm not entirely clear on what you'd like to do. Are you trying to send bulk mail or transactional one-off emails to people not on your mailing list? I think it's the latter. If you, should look at MailChimp's transactional product (formerly called Mandrill).

It's not supported by Gibbon, but you can send to it via SMTP so it's easy to use regardless.

If you're trying to send a bulk campaign to people, then you need to subscribe them to your list. You can do this with Gibbon. There are examples in the [README](http://github.com/amro/gibbon/). 

Beyond that, barring some unknown bug, Gibbon supports all features of MailChimp's API 3.0. You should read MailChimp's API documentation to see what features are supported and read Gibbon's README doc carefully to understand how to use it with MailChimp's API. Gibbon is essentially a thin/light http wrapper that exposes the API in a Ruby-esque way.

I hope that helps, but let me know if you have another question.

**Comment by tylerbhughes** [comment]
So I'm trying to do both. I'm trying to send bulk email to people not on my mailing list as well as send transaction one-off emails to people not on my mailing list.

**Comment by amro** [comment]
I see. To send bulk email you need to subscribe them to your list first -- you can do this programmatically with Gibbon. Then they'll be part of your next campaign sent to that list.

Transactional email is a separate beast. It's not something that Gibbon supports because it's not part of MailChimp's API 3, which is what Gibbon wraps/supports. You can either use MailChimp's transactional service or some other provider to send transactional mail.

**Comment by tylerbhughes** [comment]
Thanks for answering my question.
