### ISSUE TITLE
Not able to send or upsert campaigns + broken pipe error

### ISSUE THREAD

**Issue by mohnstrudel** [amro/gibbon#249]
I'm trying to do a simple testing of a campaign delivery.
`gibbon.campaigns(campaign_id).content.upsert(body: { html: "<p>A test</p>" })`
`gibbon.campaigns(campaign_id).actions.send.create`

This is my error - http://take.ms/NmFJn (basically, it's 404 - Resource not found)

My campaign_id is set up right (I receive a value - 78095). I can create a campaign and it is displayed in the browser, when logged in to mailchimp, so there is no issues there. My @gibbon object is there:
`@gibbon
=> #<Gibbon::Request:0x007f848abba218 @path_parts=[], @api_key="xxx-us16", @api_endpoint=nil, @timeout=60, @open_timeout=60, @proxy=nil, @faraday_adapter=:net_http, @symbolize_keys=false, @debug=false, @logger=#<Logger:0x007f848abba128 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x007f848abba0d8 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x007f848abba060 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007f848abba010>>>>
`

This is my full code of the model which is responsible for newsletter delivery:
```class Mailchimp

  def initialize(params)
    @gibbon = Gibbon::Request.new(api_key: Figaro.env.mailchimp_api_key)
    @title = params[:title]
    @body = params[:body]
  end

  def deliver_campaign
    campaign_id = create_campaign
    @gibbon.campaigns(campaign_id).content.upsert(body: { html: "<p>A test</p>" })
    begin
      @gibbon.campaigns(campaign_id).actions.send.create
    rescue Gibbon::MailChimpError => e
      puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
    end
  end
  def create_campaign
    recipients = {
      list_id: Figaro.env.mailchimp_list_id
    }
    settings = {
      subject_line: @title,
      title: @title,
      from_name: "Anton Kosherstin",
      reply_to: "anton@yadadya.com"
    }
    body = {
      type: "regular",
      recipients: recipients,
      settings: settings,
      html: @body
    }
    begin
      response = @gibbon.campaigns.create(body: body)
      return response.body['web_id']
    rescue Gibbon::MailChimpError => e
      puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
    end
  end
end
```

Even if I use `Gibbon::Request` I still get the same error (campaign 78123 sure does exist - http://take.ms/QkK9V) :
```Gibbon::Request.campaigns("78123").content.upsert(body: { html: "<p>A test</p>" })
Gibbon::MailChimpError: the server responded with status 404 @title="Resource Not Found", @detail="The requested resource could not be found.", @body={:type=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", :title=>"Resource Not Found", :status=>404, :detail=>"The requested resource could not be found.", :instance=>""}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Resource Not Found\",\"status\":404,\"detail\":\"The requested resource could not be found.\",\"instance\":\"\"}", @status_code=404
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/api_request.rb:134:in `handle_error'
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/api_request.rb:44:in `rescue in put'
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/api_request.rb:38:in `put'
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/request.rb:59:in `upsert'
	from /Users/mohnstrudel/testprojects/yadadya/kosher.ru/app/models/mailchimp.rb:12:in `deliver_campaign'
```

Second problem: whenever I'm trying to `retrieve` something, I get the broken pipe error or the 'the end of file is reached' error:
```@gibbon.lists.retrieve
Gibbon::MailChimpError: end of file reached @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/api_request.rb:134:in `handle_error'
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/api_request.rb:57:in `rescue in get'
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/api_request.rb:51:in `get'
	from /Users/mohnstrudel/.rvm/gems/ruby-2.4.1/gems/gibbon-3.1.0/lib/gibbon/request.rb:65:in `retrieve'
	from /Users/mohnstrudel/testprojects/yadadya/kosher.ru/app/models/mailchimp.rb:20:in `deliver_campaign'
```

**Comment by amro** [comment]
If [MailChimp's documentation](https://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/) is to be trusted, the campaigns endpoint does not support upsert (HTTP PUT) for updating a campaign's content.

You can ask them if they're willing to add that, though I suspect it's intentional given campaigns are sort of heavier weight objects than [members](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/).

I believe that's why you're getting a 404.

**Comment by mohnstrudel** [comment]
But there is this code in your documentation:
```
body = {
  template: {
    id: template_id,
    sections: {
      "name-of-mc-edit-area": "Content here"
    }
  }
}

gibbon.campaigns(campaign_id).content.upsert(body: body)
```

However, actually, yesterday I managed to make it work. What I did was to recreate the initializer with this code:
```
Gibbon::Request.api_key = Figaro.env.mailchimp_api_key
Gibbon::Request.open_timeout = 15
Gibbon::Request.symbolize_keys = true
Gibbon::Request.debug = false
```

Then, in all my requests, I use `Gibbon::Request` instead of `gibbon.something` or `@gibbon.something`. Now even the retrieves work!

**Comment by amro** [comment]
I see. Thanks for the correction. I believe I would have tested the examples in the readme though some were added by other folks. I wonder why the documentation doesn't show PUT as an option then.

As for making static calls vs an instance -- well that shouldn't matter. But instances of Gibbon shouldn't be reused. Were you doing that before?

I suspect the issue was probably just your using the wrong id. Anyway, I'm glad you figured it out.
