### ISSUE TITLE
Question about E-Commerce API

### ISSUE THREAD

**Issue by nfriend21** [amro/gibbon#251]
Does this gem currently allow you to make any E-Commerce API calls?  

Im looking at the mailchimp docs here - https://developer.mailchimp.com/documentation/mailchimp/guides/getting-started-with-ecommerce/

Sorry if this is a dumb question, and thanks so much for your help!

**Comment by amro** [comment]
Yes, gibbon supports any MailChimp API 3 call. Iirc there’s a section in the readme explaining how to map their api doc onto gibbon’s expected call chain. Anywho, yep it should work fine for you!

Thanks,
Amro

**Comment by amro** [comment]
@nfriend21 I wanted to follow up to make sure you're all set here. Are you?

**Comment by tedma4** [comment]
What is the correct way to make a request to the ecommerce store? I'm trying to create a store with

    $gibbon.ecommerce.create(body: {id: "store_num_1", name: "Store", list_id: "list_id", currency_code: "USD"})

But I get the Error
    
    Gibbon::MailChimpError: the server responded with status 405 @title="Method Not Allowed", @detail="The requested method and resource are not compatible. See the Allow header for this resource's available methods.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Method Not Allowed", "status"=>405, "detail"=>"The requested method and resource are not compatible. See the Allow header for this resource's available methods."}}", @status_code=405

**Comment by amro** [comment]
Hi @tedma4. In the future please create a new issue instead of reusing an old one.

You’re POSTing to /ecommerce/, but I don’t think that endpoint exists (looking at MC’s docs).

/ecommerce/stores exists and I think that’s what you are trying to call. So try 

```$gibbon.ecommerce.stores.create(...)```

https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/
