### ISSUE TITLE
Gibbon generating repeat URLs that result in 404s on the Mailchimp side

### ISSUE THREAD

**Issue by zachfeldman** [amro/gibbon#252]
Hey @amro , thanks again for a great gem!

I'm having an interimittent issue where Gibbon seems to be generating 404 resource not found errors with strange URLs being requested.

With debug on, it generates URLs like this for like, 1% of requests:
https://us11.api.mailchimp.com/3.0/lists/<list id>/members/lists/<list id>/members/lists/<list id>/members

Sometimes this is after a 400 member exists error.

My code to subscribe is like so:

```
  GIBBON_CLIENT = Gibbon::Request.new(api_key: ENV['MAILCHIMP_KEY'])

  GIBBON_CLIENT.lists(list_id).members.create(body: {
        email_address: params[:email],
        status: "subscribed",
        merge_fields: {
          ZIP: params[:zip]
        }
      })
```

`params[:email]` is equal to a valid email, like test@test.com.

In most cases the member is subscribed anyway (perhaps they try again when it fails). But it is an error nonetheless.

Any ideas what might be causing this behavior?

**Comment by amro** [comment]
@zachfeldman Howdy. Sorry you're having trouble. I think the problem (well, I am assuming given the code you pasted) is you may be reusing gibbon instances. You should create a new request every time you want to hit the API. I can explain why (implementation detail), if you're curious, once you've confirmed you're doing this.

**Comment by zachfeldman** [comment]
I am doing this! Can you explain why? Glad to know it's a fairly easy fix.

**Comment by amro** [comment]
Yup. Gibbon is built on the builder pattern so it can build HTTP paths dynamically based on one's ruby call chain. That's how it supports arbitrary paths/APIs without needing an update and also without having to declare a specific API for every API endpoint MailChimp makes available. Once a terminating verb is hit, the path is constructed and Gibbon attempts to make a request. At that point the internal path is cleared.

You should technically be able to reuse requests so long as you make sure you always terminate with a verb, but there might be some weirdness with shared instances and concurrency there so I don't recommend it. You'd have to synchronize access to a given instance in those cases. More trouble than it's worth.

For instance: 

```
gibbon.lists(list_id).members.create(...)
```

will map to

```
POST /lists/<list_id>/members
```

Where create is the verb mapped onto HTTP POST.

The whole idea might be a bit of a hack, I admit, but it works quite well for folks and simplifies maintenance.

You can see the details [here](https://github.com/amro/gibbon/blob/master/lib/gibbon/request.rb).

**Comment by zachfeldman** [comment]
Got it! I just pushed a fix on my end to not re-instantiate. Going to close this for now but will reopen if it occurs.
