### ISSUE TITLE
APIRequest#parse_response bug

### ISSUE THREAD

**Issue by dwlknsn** [amro/gibbon#253]
Hi there!  Thanks for all the hard work in making this gem available. Hoping I can help with a small fix.

I noticed the following code in the [`APIRequest`](https://github.com/amro/gibbon/blob/master/lib/gibbon/api_request.rb#L169-L172) class, which appears to contain a bug:

```
error = MailChimpError.new("Unparseable response: #{response_body}")
error.title = "UNPARSEABLE_RESPONSE"
error.status_code = 500
raise error
```

As far as I can see, the [`MailChimpError`](https://github.com/amro/gibbon/blob/master/lib/gibbon/mailchimp_error.rb#L3) class does not have any public api to set these attributes outside of passing them in the `params` argument to the initializer, so this method of assignment will raise a NoMethodError. Example:

```
error = Gibbon::MailChimpError.new
=> #<Gibbon::MailChimpError:  @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil>

error.title = "UNPARSEABLE_RESPONSE"
NoMethodError: undefined method 'title=' for #<Gibbon::MailChimpError:0x007fb8e06fc868>
Did you mean?  title

error.status_code = 500
NoMethodError: undefined method 'status_code=' for #<Gibbon::MailChimpError:0x007fb8e06fc868>
Did you mean?  status_code
```

I'm happy to put a PR together, but I wondered whether you prefer to assign the values in the params at the point where the error class is instantiated:

```
error_params = { title: "UNPARSEABLE_RESPONSE", status_code: 500 }
error = MailChimpError.new("Unparseable response: #{response_body}", error_params)
raise error
```
...or to make those attributes writeable?

Let me know what you think and what the best way is for me to submit a fix.

All the best,
DW

**Comment by amro** [comment]
Hi @dwlknsn. Thanks! This is a great find. Yes, I'd appreciate a PR to fix this. My preference is passing the params at initialization time one or way or another. Either adding another initializer that takes the individual parameters or what you've shown in your second example.

Could I trouble you to add a test for this too? (Just initializing an error and making sure the attributes are set is good enough here.)

Thank you!

**Comment by dwlknsn** [comment]
Hey @amro - no problem, happy to help :)

[PR here](https://github.com/amro/gibbon/pull/254). Welcome your feedback.

**Comment by amro** [comment]
Thanks! I just merged the PR. I'll release an update with it shortly.

**Comment by amro** [comment]
[Gibbon 3.1.1](https://github.com/amro/gibbon/tree/v3.1.1) released. Thanks for the PR!

**Comment by dwlknsn** [comment]
Awesome!  😄
