### ISSUE TITLE
Test email behaviour

### ISSUE THREAD

**Issue by bluciam** [amro/gibbon#256]
Checking to see if it is a bug or a feature.

The following code:

      body = {
          test_emails: test_emails,
          send_type: "html"
      }

      result = @gibbon.campaigns(campaign_id).actions.test.create(body: body)

when the `test_emails` is empty, sends the test campaing to the whole list in the campaign. 

Is this the desired behaviour?

**Comment by amro** [comment]
This is a question for MC’s API team. Is it documented, by chance? It’s not a function of gibbon.

Thanks,
Amro

**Comment by bluciam** [comment]
Thanks for the comment. Did not see anything in the documentation. Digging deeper and asking...
