### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by mattmanning** [amro/gibbon#259]
Mailchimp will soon deprecate TLS 1.0 and 1.1 support: https://devs.mailchimp.com/blog/tls-1-0-and-1-1-deprecation/

What's the best way to enforce TLS 1.2 with gibbon?

**Comment by amro** [comment]
FYI I've released Gibbon 3.2 including this change. I went w/ 3.2 b/c it could be a breaking change depending on one's server configuration.
