### ISSUE TITLE
Partial Response Implementation

### ISSUE THREAD

**Issue by ArchieJG** [amro/gibbon#263]
Mail Chimp's API has a feature to get partial responses to speed up the response of the API. It's explained [here](http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3#query-string-parameters)
Any chance of getting this implemented into Gibbon? Looking at the code and how `path_parts` works I'm guessing it would incorporate quite nicely. I'm tempted to attempt to implement it myself, just wondering if you had any plans already for it?

**Comment by amro** [comment]
It looks like they’re just parameters. This should already be possible by passing what amounts to a CSV string. Have you tried it, by chance?

Thanks,
Amro

**Comment by ArchieJG** [comment]
I had a quick play but couldn't get it to work, any chance you could provide an example? I'll keep trying in the meantime and will update the issue if I find anything :smile: 
Thanks for the quick response

**Comment by ArchieJG** [comment]
Figured it out! Thanks, didn't notice you already had an example in the docs, my bad! :smile:

**Comment by amro** [comment]
No problem!

Thanks,
Amro
