### ISSUE TITLE
Please take down

### ISSUE THREAD

**Issue by poolscapes** [amro/gibbon#266]
please take down

**Comment by poolscapes** [comment]
[2018-04-13 22:08:09] ERROR: Form 2288 > MailChimp API error: 404 Not Found. Resource Not Found. The requested resource could not be found.
Request: PUT https://us9.api.mailchimp.com/3.0/lists/703ba6c869/members/e0a2fa9181a2282d80417169b06223b0 - {"email_address":"conn**@ge**********.com","interests":{},"merge_fields":{"FNAME":"jesi","LNAME":"l","MMERGE3":"95826"},"status":"pending","email_type":"html","ip_signup":"23.30.43.145"}
Response: 404 Not Found - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Resource Not Found","status":404,"detail":"The requested resource could not be found.","instance":"2feb9603-a97a-4e4c-947b-b04fd8f360a4"}

**Comment by amro** [comment]
Hi there,

The latest version of Gibbon is 3.2.0. What did you update to 4.2.1?

Thanks,
Amro

**Comment by poolscapes** [comment]
CRAP- posted in the wrong forum. I am sorry.

**Comment by amro** [comment]
No problem at all 

Thanks,
Amro
