### ISSUE TITLE
404 error when looping over multiple lists to unsubscribe a member

### ISSUE THREAD

**Issue by catley85** [amro/gibbon#269]
## Summary

I have multiple MailChimp lists that can potentially include the same member, although the member I am trying to unsubscribe is not part of EVERY list.
I have stored a list of all my list IDs in an array and am then iterating over those lists to unsubscribe an instance of a member. 
The issue arises when the iteration hits a list that does not contain the member to be unsubscribed, the following 404 error is thrown. 
```
the server responded with status 404 @title="Resource Not Found", @detail="The requested resource could not be found.",
@body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/",
 "title"=>"Resource Not Found", "status"=>404, "detail"=>"The requested resource could not be found.",
"instance"=>"1203266a-4b3e-463e-94a5-4727ccddb14c"},
@raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Resource Not Found\",\"status\":404,\"detail\":\"The requested resource could not be found.\",\"instance\":\"1203266a-4b3e-463e-94a5-4727ccddb14c\"}",
@status_code=404
```
It feels like there should be a way to retrieve lists that only contain an instance of a member, is this something that already exists? 

NOTE: The error does not occur if a member is part of every list.

**Comment by amro** [comment]
Try wrapping your call in a try/catch instead of making a second request first

Thanks,
Amro
