### ISSUE TITLE
Can't save tags

### ISSUE THREAD

**Issue by heaven** [amro/gibbon#274]
This doesn't work:

```ruby
gibbon.lists(list_id).members(lower_case_md5_hashed_email_address).update(body: { tags: ["Tag 1", "Tag 2", "Tag 3"]})
```

Tags only saved when upserting and if a member doesn't exist.

**Comment by victorsosa** [comment]
Try something like this
```
gibbon.lists(list_id).members(Digest::MD5.hexdigest(email)).tags.create(
  body: {
    tags: [{name:"referred-from-xyz", status:"active"},{name:"pro-plan",status:"active"}]
  }
)
```

**Comment by heaven** [comment]
Thank you, also figured this out looking at the Interests instructions in the README and API docs.

**Comment by timokleemann** [comment]
I am getting a `Method Not Allowed` when using the suggested code above.

Omitting the `.tags` method removes the error but doesn't save the tags either.

I also looked at the sections in the [MailChimp API](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/) that heaven talks about but couldn't find anything in there.

What am I missing here?

**Comment by victorsosa** [comment]
@timokleemann plase post you call

**Comment by timokleemann** [comment]
OK, here we go:

`gibbon.lists(list_id).members(lower_case_md5_hashed_email_address).tags.update(:body => {:tags => [{name:"Free", status:"active"}]})`

**Comment by victorsosa** [comment]
The Doc said that is only support POST and GET so it is true that update method(PUT) is not valid

**Comment by timokleemann** [comment]
No problem. So is there no way to update the `tags` on a member through Gibbon?
It seems that @heaven got it to work... I wonder how he did it.

**Comment by heaven** [comment]
@timokleemann, I figured out that you have to update tags similar to how you would update interests, and simply passing an array of tag names only work when creating a member. My code is below:

```ruby
member =
  gibbon.lists(@list_id).members(record.address_hash).upsert(record.to_mailchimp).body

existing_tags = member[:tags].map { |t| t[:name] }

if existing_tags.present? or record.tags.present?
  deleted_tags = existing_tags - record.tags
  tags         = record.tags.map { |t| { name: t, status: "active" } } +
                  deleted_tags.map { |t| { name: t, status: "inactive" } }

  gibbon.lists(@list_id).members(record.address_hash).tags.create(body: { tags: tags })
end
```

**Comment by timokleemann** [comment]
Thanks a lot, @heaven! 

I ended up using *interests* rather than *tags* and hard-coded the *interest IDs* into my Rails app. That's not very elegant but reduces the number of calls to the MailChimp API.

**Comment by ParthivSavani** [comment]
> Try something like this
> 
> ```
> gibbon.lists(list_id).members(Digest::MD5.hexdigest(email)).tags.update(
>   body: {
>     tags: [{name:"referred-from-xyz", status:"active"},{name:"pro-plan",status:"active"}]
>   }
> )
> ```

I'm trying this ```tags: [{name:"Has Password", status:"active"}]``` but it doesn't work. Please help
