### ISSUE TITLE
upsert doesn't update record

### ISSUE THREAD

**Issue by olegsobchuk** [amro/gibbon#279]
I can insert new record to MailChimp with `upsert`, but when I try to update the same record, I get error with message 

`Gibbon::MailChimpError (the server responded with status 400 @title="Member Exists", @detail="user@some.com is already a list member. Use PUT to insert or update list members."`

And `update` works. Is `upsert` can update record, as it says in documentation?

**Comment by amro** [comment]
Hi @olegsobchuk.

Can you paste the snippet/call you're making with Gibbon?

Are you explicitly setting `status: "subscribed"` already? If not can you try doing so ?

**Comment by olegsobchuk** [comment]
@amro hi!

```
def join_or_update
  lists(list_id).members(md5_email).upsert(
      body: {
        email_address: user.email,
        status: 'subscribed',
        merge_fields: merge_vars
      }
    )
end

def merge_vars
  {
    FNAME: user.first_name,
    LNAME: user.last_name
  }
end

def list(list_id)
  Gibbon::Request.lists(list_id)
end
```
a little bit simplified but actually the same

**Comment by amro** [comment]
Upsert does indeed map to a `PUT` request as you can see here. Two things to try:

1. Can you try returning a new request instead of making a static call in your `list()` method? Gibbon adds portions of the call chain to an array then converts that to a path before making a request. I wonder if there's a mistake in how this is handled for static calls.

2. Can you please try setting `.debug = true` on your gibbon request before making the request to make sure Gibbon is doing the right thing?

**Comment by olegsobchuk** [comment]
@amro  I'm not really understand, what do you mean with "`returning a new request instead of making a static call in your list() method`"

**Comment by amro** [comment]
I see. Sorry for not being clear. Try this:

```
def join_or_update
  lists(list_id).members(md5_email).upsert(
      body: {
        email_address: user.email,
        status: 'subscribed',
        merge_fields: merge_vars
      }
    )
end

def merge_vars
  {
    FNAME: user.first_name,
    LNAME: user.last_name
  }
end

def list(list_id)
  Gibbon::Request.new(api_key: <your_api_key>).lists(list_id)
end
```

**Comment by olegsobchuk** [comment]
@amro Oh... I see, what you mean. I'll check it during weekend.

**Comment by olegsobchuk** [comment]
@amro IT WORKS!!! THANKS!

maybe it will be helpful for someone in the future.

my not working implementation:

I used to initialize `Gibbon` in `config/initializers` 
```
Gibbon::Request.api_key = Rails.application.secrets.mailchimp_api_key
Gibbon::Request.symbolize_keys = true

```
and then I used to use it in the needed place

```
def list(list_id)
  Gibbon::Request.lists(list_id)
end
```
in this case `upsert` didn't work

working implementation:

```
def list(list_id)
  Gibbon::Request.new(
    api_key: Rails.application.secrets.mailchimp_api_key,
    symbolize_keys: true
  ).lists(list_id)
end
```

and in this case `upsert` works. And I don't need `subscribe`, `update` and `unsubscribe` separate methods. Now I use a single method, where I just send user's `status`

Thanks, @amro  for help!

Cheers!

**Comment by amro** [comment]
Great. Glad to hear it
