### ISSUE TITLE
Retrieve does not fetch all records

### ISSUE THREAD

**Issue by krettan** [amro/gibbon#280]
The readme is a bit misleading since it states `gibbon.lists(list_id).members.retrieve` will get all subscribers for a list when it in fact will only get the first 10 (default page size).

Is this expected and the readme should be updated or some sort of paging be added to the retrieve call?

**Comment by amro** [comment]
I don't have a problem with the README having a general call-out about the number of records returned bing limited by the APIs.

Paging should already be supported as gibbon maps Ruby syntax directly onto MailChimp's API via some method_missing magic. There's very little special casing or business logic in the gem itself.

Generally speaking, the README is there to help one get started and not meant to be the documentation for Mailchimp's API though.

**Comment by krettan** [comment]
I agree with you that the exact number is irrelevant. I just got stuck on the wording since a single call didn't return all available results from the API. Feel free to close the PR and this issue if you disagree!

**Comment by amro** [comment]
Merged. Thank you for updating the readme.
