### ISSUE TITLE
Cannot set faraday_adapter globally

### ISSUE THREAD

**Issue by dpashkevich** [amro/gibbon#287]
The docs say:

> You can set api_key, timeout, open_timeout, **faraday_adapter**, proxy, symbolize_keys, logger, and debug globally:

But doesn't appear to be the case:

```
[11] pry(main)> ::Gibbon::Request.faraday_adapter = :em_synchrony_keepalive
=> :em_synchrony_keepalive
[12] pry(main)> new_request = ::Gibbon::Request.new
=> #<Gibbon::Request:0x00007fbdc8ad19d8
 @api_endpoint=nil,
 @api_key=nil,
 @debug=false,
 @faraday_adapter=:net_http,
 <...>
```

Notice the line: `@faraday_adapter=:net_http,`.

I can still successfully set the faraday adapter in the request constructor though:
```
request = ::Gibbon::Request.new(faraday_adapter: :em_synchrony_keepalive)
```

**Comment by amro** [comment]
Thanks for your patience. This seems like a bug. I’ll investigate tonight after work.

**Comment by amro** [comment]
Confirmed this is a problem. Will work on a fix

**Comment by amro** [comment]
@dpashkevich Thanks for the bug report! I've pushed version 3.3.1 to address this.
