### ISSUE TITLE
Changelog updates for 3.3.2

### ISSUE THREAD

**Issue by danielpowell4** [amro/gibbon#291]
Could be missing something but I think the recent release missed including a corresponding update to the changelog

https://github.com/amro/gibbon/blob/master/CHANGELOG.md

Personally not sure how much of this (the linked unreleased) is included:

https://github.com/amro/gibbon/compare/v3.1.0...HEAD

**Comment by amro** [comment]
You’re right — thanks. I’ll update this when I get a chance. tldr; is we bumped the minimum version for Faraday

**Comment by danielpowell4** [comment]
Thanks for updating!
