### ISSUE TITLE
NameError: uninitialized constant Faraday::Error::ClientError

### ISSUE THREAD

**Issue by brian-kephart** [amro/gibbon#292]
Related to #289.
Gibbon 3.3.2
Faraday 1.0.0

```
File "/app/vendor/bundle/ruby/2.7.0/gems/gibbon-3.3.2/lib/gibbon/api_request.rb", line 114, in handle_error
File "/app/vendor/bundle/ruby/2.7.0/gems/gibbon-3.3.2/lib/gibbon/api_request.rb", line 57, in rescue in get
File "/app/vendor/bundle/ruby/2.7.0/gems/gibbon-3.3.2/lib/gibbon/api_request.rb", line 51, in get
File "/app/vendor/bundle/ruby/2.7.0/gems/gibbon-3.3.2/lib/gibbon/request.rb", line 65, in retrieve
```

Here's the twist: earlier in the call stack, this action generated a `Faraday::TimeoutError: Net::ReadTimeout with #<TCPSocket:(closed)>`. So, this issue arises when an error occurs that is **not** `ClientError`,  causing the second half of [this expression](https://github.com/amro/gibbon/commit/2bd9a294a5ad4c94477a749d6e74fb875a646000#diff-84866caf087880c9099d253efc60d80eR114) to be executed.

It looks to me like since the Faraday requirement has been updated, the reference to `Faraday::Error::ClientError` and the associated comment are obsolete and can be safely removed. That's just me glancing at it though, so I'd appreciate a look from someone who knows the repo.

**Comment by amro** [comment]
You are correct. Thank you so much for the patch. I’ll test and release a little later (maybe tonight or tomorrow morning).

**Comment by robert-hromej** [comment]
> You are correct. Thank you so much for the patch. I’ll test and release a little later (maybe tonight or tomorrow morning).

waiting for your release. 
thanks)

**Comment by amro** [comment]
Thanks for the reminder. I’ve had a busy couple of days with work. I’ll take a look now.
