### ISSUE TITLE
3.4.1 Causes 401: API Key Invalid

### ISSUE THREAD

**Issue by GabeIsman** [amro/gibbon#305]
After upgrading to 3.4.1 today, I started getting errors from Mailchimp that looked like this
```
#<Gibbon::MailChimpError: the server responded with status 401 @title="API Key Invalid", @detail="Your request did not include an API key.", @body={:type=>"https://mailchimp.com/developer/marketing/docs/errors/", :title=>"API Key Invalid", :status=>401, :detail=>"Your request did not include an API key.", :instance=>"86f56459-56c1-e225-1bc7-169060c257ff"}, @raw_body="{\"type\":\"https://mailchimp.com/developer/marketing/docs/errors/\",\"title\":\"API Key Invalid\",\"status\":401,\"detail\":\"Your request did not include an API key.\",\"instance\":\"86f56459-56c1-e225-1bc7-169060c257ff\"}", @status_code=401>
```
After doing some digging and trying the obvious things I noticed that the release had made some changes to the faraday basic_auth call. Confirmed that rolling back to 3.4.0 fixed the problem. Just undoing the change made to `APIRequest` in https://github.com/amro/gibbon/commit/902d61c38976d121f0e272b0b1383afa448fbd0c was enough actually.

**Comment by amro** [comment]
No problem. Do you recall which dependencies caused issues for you? I’m wondering if I can drop versions on them without other trouble

**Comment by austinwalter** [comment]
I'm seeing this same issue too. I'm downgrading back to my previous version, but then I'll try v3.4.2 and see if that fixes it.

**Comment by amro** [comment]
3.4.2 should resolve it, yep. Please let me know if you run into trouble

**Comment by austinwalter** [comment]
v3.4.2 seems to be working. Thanks.
