### ISSUE TITLE
Gibbon doesn't work with Faraday 2.x

### ISSUE THREAD

**Issue by pedantic-git** [amro/gibbon#319]
Hi Gibbon maintainers!

In my last Gem update I accidentally bumped Faraday to 2.x because Gibbon's version constraint is `>= 1.0`.

Unfortunately, [this breaking change](https://lostisland.github.io/faraday/middleware/authentication) in Faraday 2.x doesn't work for Gibbon because it uses the `conn.request :basic_auth` syntax. The error I get when trying to call `#upsert` is:

```
/app/vendor/bundle/ruby/3.0.0/gems/gibbon-3.4.2/lib/gibbon/api_request.rb:134:in `handle_error': :basic_auth is not registered on Faraday::Request @title=nil, @detail=nil, @body=nil, @raw_body=nil, @status_code=nil (Gibbon::MailChimpError)
/app/vendor/bundle/ruby/3.0.0/gems/faraday-2.1.0/lib/faraday/middleware_registry.rb:57:in `lookup_middleware': :basic_auth is not registered on Faraday::Request (Faraday::Error)
```

Putting `gem 'faraday', '~> 1.8'` in my Gemfile works for now but others may have the same issue.

Thanks for looking at it!

**Comment by amro** [comment]
Hi @pedantic-git, thanks for the heads up. Will investigate soon. There is a closed issue for 3.4.1 you might read for context, but it won't help your situation.

**Comment by amro** [comment]
My apologies -- someone recently merged a PR to address this, but as I was on holiday I did not release an updated build. I'll do so now. https://github.com/amro/gibbon/pull/318

**Comment by amro** [comment]
Thanks again for the bug report. Please try Gibbon 3.4.3, which should address your concern

**Comment by pedantic-git** [comment]
Thank you! Sorry for not checking if there were already closed issues before reporting - it was late!
