### ISSUE TITLE
Updating from 1.x: How to replace .lists.merge_var_add?

### ISSUE THREAD

**Issue by SubandiK** [amro/gibbon#326]
Hi, thanks for this gem!
I'm in the process of updating versions and the old code base used to do something like
```
Gibbon::API.new(list.mailchimp_api_key).lists.merge_var_add(id: list.mailchimp_list_id, tag: 'PLAN', name: 'Plan')
```
which went to `api.mailchimp.com/2.0/lists/merge-var-add`

I haven't found a replacement in the new version that I could call on e.g.

```
 Gibbon::Request.new(api_key: list.mailchimp_api_key)
```

How can I do this?

**Comment by amro** [comment]
Hi @SubandiK. As Gibbon wraps Mailchimp's API directly, you'll want to look at their API docs for merge fields. There's some info on how to [add merge fields](https://mailchimp.com/developer/marketing/api/list-merges/add-merge-field/) there that should help.

It should be something like 

```
gibbon.lists(list_id).merge_fields.create(body: {...})
```

where `body` is populated w/ the params based on the API docs

**Comment by SubandiK** [comment]
Thanks, yeah that will work too! Was just thinking I'm missing something obvious here.
