### ISSUE TITLE
MailChimp API through proxy

### ISSUE THREAD

**Issue by nicholaide** [amro/gibbon#38]
According to the post found in [their google group](https://groups.google.com/forum/?fromgroups=#!topic/mailchimp-api-discuss/miEFvkgz1DY), the MailChimp API does not support communicating via a proxy.

I have read that there are some patches like [this one] (http://drupal.org/node/1708226), and I would like to know if it possible to implement this in Gibbon. If so, kindly point me to the "right direction", i.e. which modules and files I should look into, and then I will make a pull request, assuming you want this workaround to be part of the gem.

Thank you.

**Comment by amro** [comment]
This is quite an old ticket but Gibbon 2.2.0 has just been released with Proxy support thanks to a contribution by @scottwater.
