### ISSUE TITLE
Install broken because of ruby version required by httparty

### ISSUE THREAD

**Issue by mig-hub** [amro/gibbon#78]
Hello,

My install just broke because my project is using Ruby 1.9.2 and the last HTTParty requires Ruby version 1.9.3

Not sure how you want to fix this, but I guess the gemspec of Gibbon should either specify the same Ruby version, or specify a HTTParty version prior to this change (like 0.11.0).

This is what I did to deal with the problem:
Instead of letting Bundler deal with this particular dependency, I did `gem install httparty -v '0.11.0'` and then `gem install gibbon`.

mig

**Comment by amro** [comment]
Closing this - as it's no longer relevant. Apologies for not figuring out a worth while solution. Gibbon v2 is out now.
